### ISSUE TITLE
Ladle breaks when next/image component is imported

### ISSUE THREAD

**Issue by davidpfahler** [tajo/ladle#100]
I have stories for simple components that work fine. But once I click on a story for a component that uses the `next/image` component, nothing renders and ladle is broken until reload. Once I clock on a story with `next/image` the following error occurs in the console:

```
react.development.js:1309 Uncaught ReferenceError: process is not defined
    at node_modules/next/dist/client/normalize-trailing-slash.js (normalize-trailing-slash.ts:12:43)
    at __require (chunk-MYIE5J7A.js?v=88870cd9:25:50)
    at node_modules/next/dist/shared/lib/router/router.js (router.ts:13:50)
    at __require (chunk-MYIE5J7A.js?v=88870cd9:25:50)
    at node_modules/next/dist/client/link.js (link.tsx:11:37)
    at __require (chunk-MYIE5J7A.js?v=88870cd9:25:50)
    at node_modules/next/link.js (link.js:1:18)
    at __require (chunk-MYIE5J7A.js?v=88870cd9:25:50)
    at dep:next_link:1:16
node_modules/next/dist/client/normalize-trailing-slash.js @ normalize-trailing-slash.ts:12
__require @ chunk-MYIE5J7A.js?v=88870cd9:25
node_modules/next/dist/shared/lib/router/router.js @ router.ts:13
__require @ chunk-MYIE5J7A.js?v=88870cd9:25
node_modules/next/dist/client/link.js @ link.tsx:11
__require @ chunk-MYIE5J7A.js?v=88870cd9:25
node_modules/next/link.js @ link.js:1
__require @ chunk-MYIE5J7A.js?v=88870cd9:25
(anonymous) @ dep:next_link:1
react_devtools_backend.js:3973 The above error occurred in one of your React components:

    at Lazy
    at Provider (http://localhost:61000/generated/generated-list.tsx:114:28)
    at Suspense
    at ErrorBoundary (http://localhost:61000/src/error-boundary.tsx:4:5)
    at Story (http://localhost:61000/src/story.tsx:11:18)
    at main
    at App (http://localhost:61000/src/app.tsx:24:41)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

Here is a screenshot for better readability:

<img width="929" alt="Screen Shot 2022-04-14 at 17 43 33" src="https://user-images.githubusercontent.com/908242/163425712-c3c421d2-6b2a-428d-86c0-422b8ec4f24f.png">

**Comment by tajo** [comment]
> react.development.js:1309 Uncaught ReferenceError: process is not defined

It seems that browser is trying to use `process`? You might need to replace with something: https://www.ladle.dev/docs/config#global-constant-replacements

Next.js is probably doing some sort of build time things inside the next/image.

**Comment by jeremytenjo** [comment]
Any updates on this issue?

**Comment by tajo** [comment]
This is a good issue for someone to look into. `next/image` assumes that it's used inside of Next.js so there's some hacking needed, check this:

https://dev.to/jonasmerlin/how-to-use-the-next-js-image-component-in-storybook-1415

If we need to expose some APIs to allow these hacks in Ladle, I'm happy to add those.

**Comment by jeremytenjo** [comment]
Thanks @tajo . I will look into it and post any finding I have.

**Comment by jeremytenjo** [comment]
We need to inject process in the build step.

I tried using the `NodeGlobalsPolyfillPlugin` plugin in `optimizeDeps` following this [tutorial](https://medium.com/@ftaioli/using-node-js-builtin-modules-with-vite-6194737c2cd2) but process is still not defined.

```js
import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill'

export default {
  stories: 'src/**/*.stories.{js,jsx,ts,tsx}',
  serve: {
    open: 'none',
    port: 61000,
  },
  optimizeDeps: {
    esbuildOptions: {
      plugins: [
        NodeGlobalsPolyfillPlugin({
          process: true,
          define: { process: {} },
        }),
      ],
    },
  },
}
```

**Comment by joe-bell** [comment]
Not the prettiest solution, but works for me:

```js
// .ladle/config.mjs
export default {
  define: {
    "process.env": process.env,
  },
};
```

**Comment by jeremytenjo** [comment]
Thanks @joe-bell, that worked for me as well.

To `unoptimized` next/image, I wrapped it in my own `Image.tsx` component. Replace `XSTORYBOOK_EXAMPLE_APP` with a Ladle environment variable.  

`Image.tsx` 

```js
import React from 'react'
import NextImage, { type ImageProps as NextImageProps } from 'next/image'

export type ImageProps = NextImageProps

const isStorybook = process?.env?.hasOwnProperty('XSTORYBOOK_EXAMPLE_APP') || false

const storybookProps = {
  unoptimized: true,
  blurDataURL:
    'data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAADAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAbEAADAAMBAQAAAAAAAAAAAAABAgMABAURUf/EABUBAQEAAAAAAAAAAAAAAAAAAAMF/8QAFxEAAwEAAAAAAAAAAAAAAAAAAAECEf/aAAwDAQACEQMRAD8Anz9voy1dCI2mectSE5ioFCqia+KCwJ8HzGMZPqJb1oPEf//Z',
}

export default function Image(props: ImageProps) {
  return <NextImage {...props} {...(isStorybook ? storybookProps : {})} />
}
```

**Comment by joe-bell** [comment]
Nice workaround, thanks @jeremytenjo!

I think long term an option like Storybook's workaround would be preferred to keep mock/ladle props out of the bundle

```js
// .storybook/preview.js

import * as NextImage from "next/image";

const OriginalNextImage = NextImage.default;

Object.defineProperty(NextImage, "default", {
  configurable: true,
  value: (props) => (
    <OriginalNextImage
      {...props}
      unoptimized
    />
  ),
});
```

Would `.ladle/components.tsx` be the best place for this? 🤔

**Comment by maksimf** [comment]
> ```js
> export default {
>   define: {
>     "process.env": process.env,
>   },
> };
> ```

I've tried that and got

> ERROR: define was removed from the Ladle config in v1. Move it to vite.config.js

After I moved this to `vite.config.js` I still get the same issue: 

![image](https://user-images.githubusercontent.com/860283/179850982-71e13576-42fa-4b8a-af45-dc78e9bab17f.png)

**Comment by bonesoul** [comment]
same with @maksimf,

```
export default {
  define: {
    "process.env": process.env,
  },
};

says `ERROR: define was removed from the Ladle config in v1. Move it to vite.config.js. https://ladle.dev/docs/config`

and im not sure how to do it with vite.config.js.
```

**Comment by maksimf** [comment]
> same with @maksimf,
> 
> ```
> export default {
>   define: {
>     "process.env": process.env,
>   },
> };
> 
> says `ERROR: define was removed from the Ladle config in v1. Move it to vite.config.js. https://ladle.dev/docs/config`
> 
> and im not sure how to do it with vite.config.js.
> ```

You have to create `vite.config.js` in your root folder, not `.laddle` with the following:

```
import { defineConfig } from "vite";

export default defineConfig({
  define: {
    "process.env": process.env,
  },
});
```

This resolves the `process is not defined` for me, but I still have [this issue with images](https://github.com/tajo/ladle/issues/204)

**Comment by miko-github** [comment]
> @bonesoul
> 
> You have to create `vite.config.js` or `vite.config.ts` in your root folder, not `.laddle` (this was what I did wrong at least) with the following:
> 
> ```
> import { defineConfig } from "vite";
> 
> export default defineConfig({
>   define: {
>     "process.env": process.env,
>   },
> });
> ```
> 
> This resolves the `process is not defined` for me, but I still have [this issue with images](https://github.com/tajo/ladle/issues/204)

Thank you @maksimf for this solution! :clap: 

this work without error of `process` definition but with `404 error` for images :sweat_smile: and didn't work with relative images path to next `public/vercel.svg`

**Comment by dominggo1999** [comment]
This is my attempt to use ladle with next js (*it will only work in development).

```jsx
import { defineConfig, ViteDevServer } from 'vite';
import queryString from 'query-string';
import path from 'path';

const mapNextJsAssets = {
  name: 'map-next-js-assets',
  configureServer(server: ViteDevServer) {
    server.middlewares.use('/', (req, res, next) => {
      const params = queryString.parse(req.url as string) || {};
      const nextImageUrl = params['/_next/image?url'] as string;

      if (nextImageUrl) {
        req.url = `/@fs/${path.resolve(__dirname, `public${nextImageUrl.replaceAll('/', '\\')}`)}`;
      }

      next();
    });
  },
};

export default defineConfig({
  define: {
    'process.env': process.env,
  },
  publicDir: 'public',
  plugins: [
    mapNextJsAssets,
  ],
});

```

**Comment by sdorra** [comment]
I found another solution which uses vite aliases to append the `unoptimized` prop to `next/image`:

**vite.config.ts**:
```ts
import path from "path";
import { defineConfig } from "vite";

export default defineConfig({
  resolve: {
    alias: {
      "next/original-image": require.resolve("next/image"),
      "next/image": path.resolve(__dirname, "./.ladle/UnoptimizedImage.tsx"),
    },
  },
  define: {
    "process.env": process.env,
  },
});
```

**.ladle/UnoptimizedImage.tsx**:

```tsx
import React from "react";
// @ts-ignore have a look in vite.config.ts
import OriginalImage from "next/original-image";

const UnoptimizedImage = (props: any) => {
  return <OriginalImage {...props} unoptimized />;
};

export default UnoptimizedImage;
```

For a more detailed description, please have a look at https://sdorra.dev/posts/2023-01-18-ladle-next-image#nextimage
