### ISSUE TITLE
Modernize our monorepo & publishing setup

### ISSUE THREAD

**Issue by tajo** [tajo/ladle#113]
It seems that [Lerna is officially dead](https://github.com/lerna/lerna/commit/8b99493ac90484e05f7ebee533c0763534d60218). It's probably a good time to modernize our setup. Tools that come in mind:

-  https://turborepo.org/
-  https://github.com/changesets/changesets
- yarn v3

**Comment by nihgwu** [comment]
https://monorepo.tools/
