### ISSUE TITLE
`--open` always created a new tab rather than re-using existing

### ISSUE THREAD

**Issue by underfisk** [tajo/ladle#125]
**Describe the bug**
Currently when we pass `--open` it will always create a new tab instead of re-using the existing tab(s)

**To Reproduce**
In any integration with Ladle, this is part of the core 

1. Create a new ladle project/use any existing 
2. Simply pass `--open` and it will create a new tab each time we start the server

**Expected behavior**
If there's already a tab on that page, simply refresh that page

@tajo I'm able to create a PR to address this

**Desktop (please complete the following information):**
  System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 18.95 GB / 64.00 GB
    Shell: 3.2.2 - /usr/local/bin/fish
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Safari: 15.4

**Comment by tajo** [comment]
Agreed this is annoying. We use [open](https://github.com/sindresorhus/open) that doesn't support this. If there is some nice cross-platform solution, it would be great to have it.
