### ISSUE TITLE
Support css.preprocessorOptions

### ISSUE THREAD

**Issue by phaistonian** [tajo/ladle#130]
**Is your feature request related to a problem? Please describe.**
Support `css.preprocessorOptions` as done in Vite.

**Describe the solution you'd like**
See above

—

I think having the capacity to provide a _middleware_ function to the config, e.g.

```js
config: currentConfig => newConfig,
````

that will transform the vite config produced by `vite-dev`, `vite-prod` would enable developers to do all they need with the Vite config.

Storybook does the same with its webpack config.

**Comment by tajo** [comment]
We are re-doing the configuration setup so the root `vite.config.js` gets picked up allowing all Vite configurations.
