### ISSUE TITLE
HMR not working as expected

### ISSUE THREAD

**Issue by underfisk** [tajo/ladle#132]
**Describe the bug**
When developing components, Ladle does not detect correctly the changes. Cloning ladle repo and playing around with the example react project leads to this same issue.

Also, something I've noticed on the source code is that it would only watch for `.stories.` and does not respect the glob we override (e.g: if I want my stories to have `.fixture` instead)

**To Reproduce**
- Open [StackBlitz example](https://stackblitz.com/edit/ladle-sspazd?file=src/basic.fixture.tsx)
- Change the component title constant or something else on the react component (in this particular use case we are trying to change in an existing story, not a new story file)

**Expected behavior**
When modifying a react component/source code it should reflect those changes, right now we only see Vite detecting those changes but nothing is actually propagated to the DOM.

**Desktop (please complete the following information):**
  System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 23.91 GB / 64.00 GB
    Shell: 3.2.2 - /usr/local/bin/fish
  Binaries:
    Node: 16.15.0 - ~/.volta/tools/image/node/16.15.0/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.5.5 - ~/.volta/tools/image/node/16.15.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Safari: 15.4

**Comment by tajo** [comment]
Can you be more specific? Is this only about the source code addon? HMR seems to be working fine for me.

Are you changing a code of an existing story? Are you creating a new story? A new story file? 

> Also, something I've noticed on the source code is that it would only watch for .stories. and does not respect the glob we override (e.g: if I want my stories to have .fixture instead)

Is this the same issue?

**Comment by underfisk** [comment]
@tajo Indeed it was a little vague therefore I have updated the initial description with a better replication.



> Can you be more specific? Is this only about the source code addon? HMR seems to be working fine for me.
> 
> Are you changing a code of an existing story? Are you creating a new story? A new story file?

I'm just changing an existing story (with a different glob), there's nothing to do with the source code addon, it's just the core functionalities of Ladle.

> Is this the same issue?

Well I'm not exactly sure but since I'm using a different glob and I saw that catch on the ids, I do believe it might be related because in our codebase none of the files/components includes the story principle (we are migrating from Cosmos)

**Comment by tajo** [comment]
Thanks for the repro. The HMR breaks when  story is created through the `bind`:

```
export const MyTest = MyComponent.bind({});
```

is used. 

It works when args are [assigned directly](https://stackblitz.com/edit/ladle-g9gqd2?file=src/basic.fixture.tsx).

This is definitely a bug.

**Comment by underfisk** [comment]
@tajo When is the next release that will include this bug fix?

**Comment by tajo** [comment]
This week for sure. Working on some other bugfixes.
