### ISSUE TITLE
Console Error is thrown using style jsx

### ISSUE THREAD

**Issue by ttristan** [tajo/ladle#142]
**Describe the bug**

A console error is thrown when `<style jsx>` is used. Setting `jsx="true"` will cause errors in TypeScript

> Warning: Received `true` for a non-boolean attribute `jsx`.
> If you want to write it to the DOM, pass a string instead: jsx="true" or jsx={value.toString()}.

<img width="734" alt="Screenshot 2022-05-17 at 15 21 22" src="https://user-images.githubusercontent.com/24268434/168820777-2096dc11-1104-4cd6-b81e-5d800144a92f.png">

<img width="880" alt="Screenshot 2022-05-17 at 15 02 21" src="https://user-images.githubusercontent.com/24268434/168817280-7d08f39d-2f1a-4563-a109-bd3304ef646d.png">

**Reproduction**
https://stackblitz.com/edit/ladle-193a77?file=src%2Fbasic.stories.tsx

**Comment by tajo** [comment]
What is this for?

**Comment by ttristan** [comment]
My bad, I assumed [styled jsx](https://github.com/vercel/styled-jsx) was supported by ladle out of the box because the styles were applied (it is a style tag after all) however without scoped classes actually created by styled jsx. 

However, I was also not able to get the styled jsx configuration to work in ladle. I updated the repro including the package and configuration:
https://stackblitz.com/edit/ladle-czgdyc?file=src%2Fbasic.stories.tsx

Probably I am missing something, so any help is welcome but I will close the issue here.
