### ISSUE TITLE
Vite Plugin vanillaExtractPlugin breaks when running via Ladle

### ISSUE THREAD

**Issue by kennetpostigo** [tajo/ladle#149]
**Describe the bug**

I'm trying to use ladle for my component stories. However my component use [vanilla-extract](https://vanilla-extract.style/) for styling. `vanilla-extract` has a[ vite plugin](https://vanilla-extract.style/documentation/setup/#vite) that works great for vite application. However, when passed to ladle config it errors out and ladle shows a blank screen.

**Reproduction**

```ts
// config.mjs
import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';

export default {
  stories: '**/*.story.{ts,tsx}',
  vitePlugins: [vanillaExtractPlugin()],
};
```

```ts
// Button.tsx
import React from 'react';
import cx from 'classnames';
import { button, ButtonVariants } from '@components/atoms/Button/Button.css';

export type ButtonProps = ButtonVariants &
  React.ButtonHTMLAttributes<HTMLButtonElement> & {};

export const Button: React.FC<ButtonProps> = ({
  className,
  size,
  color,
  children,
  ...btnProps
}) => {
  return (
    <button className={cx(button({ color, size }), className)} {...btnProps}>
      {children}
    </button>
  );
};

```

```ts
// Button.story.tsx
import React from 'react';
import { Button } from '@components/atoms/Button';

export const ButtonStory = () => (
  <div>
    <h1>Button</h1>
    <Button>Click Me</Button>
  </div>
);
```

Throws this error:
![image](https://user-images.githubusercontent.com/8888991/172026996-8c13dd06-95bf-4761-a5d5-da7b046b77b9.png)

Pointing to:
![image](https://user-images.githubusercontent.com/8888991/172027007-e4b33577-31d5-4a3f-a5b8-ad05c6c77783.png)

However this error only happens when the plugin is used with `ladle` and I don't know why. I'm not sure if I'm doing anything wrong in the configuration for ladle.

**Environment**

 - OS: macOS
 - Browser: Chrome
 - Ladle Version: 0.16.0

**Comment by tajo** [comment]
Reworking the way how Ladle (and vite plugins) can be configured right now. Will be released soon.
