### ISSUE TITLE
Integration support for Chromatic CI

### ISSUE THREAD

**Issue by probablyup** [tajo/ladle#159]
**Is your feature request related to a problem? Please describe.**
Third-party integration; Chromatic is a popular visual regression testing service that integrates directly with storybook: https://www.chromatic.com/

**Describe the solution you'd like**
It'd be awesome if there was a way that Ladle worked with this service as well, either via an adapter of some sort or working with them directly for first-party support.

**Comment by tajo** [comment]
It doesn't seem to be possible to use Chromatic with anything else than Storybook. There are some similar projects supporting Ladle out of the box: https://github.com/lost-pixel/lost-pixel
