### ISSUE TITLE
Dedupe plugins

### ISSUE THREAD

**Issue by gperl27** [tajo/ladle#168]
**Overview**

It's great that this plugin is including [vite-tsconfig-paths](https://github.com/aleclarson/vite-tsconfig-paths) by default. However, I noticed that if my local `vite-config.ts` uses this plugin, it clashes with Ladle's plugin and ultimately breaks how the modules are resolved.

**Reproduction**

Create a vite project and use `vite-tsconfig-paths`:

```
// vite.config.ts
import tsconfigPaths from 'vite-tsconfig-paths';

export default defineConfig({
    plugins: [tsconfigPaths(), /** rest plugins **/ ],
});
```

Without adding my `tsconfigPaths`, everything works fine.

**Workaround**

As a temporary workaround, I did the following:
1. Added a base config **without** `vite-tsconfig-paths` in the `plugins` prop
2. In my `vite.config.ts`, merge `vite-base.config.ts` into a config where I use `tsconfigPaths()` so my `vite serve` and `vite build` will work
3. Serve Ladle from `vite-base.config.ts` to avoid the plugin conflicts

Workaround code:
```
// vite.config.ts
import { mergeConfig } from 'vite';
import tsconfigPaths from 'vite-tsconfig-paths';
import viteBaseConfig from './vite-base.config';

export default mergeConfig(viteBaseConfig, {
    plugins: [tsconfigPaths()],
});
```

```
// vite-base.config.ts
import { defineConfig } from 'vite';

export default defineConfig({
    plugins: [/** plugins here **/
    /** rest config **/
});
```

`$ yarn ladle serve --viteConfig vite-base.config.ts`

**Comment by tajo** [comment]
There is already a check for that. If you use add that plugin on your side, you should set `root: process.cwd()` - that might be your issue?

**Comment by gperl27** [comment]
Adding your suggestion worked flawlessly. Thank you!
