### ISSUE TITLE
Import & render Ladle inside the application

### ISSUE THREAD

**Issue by d-tasevski** [tajo/ladle#176]
Hey, first and foremost, **thanks** for the great library. It's really refreshing to get up and running in mere minutes compared to the _hours_ (difficulties aside) I wasted with Storybook. 🙏 

**Is your feature request related to a problem? Please describe.**
We have a repository that's housing the shared components for all other related projects. Right now, when developing, we're running a webpack dev server so that we can modify the shared components and reflect the changes in connected apps via HMR. The "problem" is that running the dev server does not make much sense, we only need to expose the shared components federation via network, but it would be great if we could somehow import the Ladle into the root component of our shared components app, and render it there as the main app while shared components dev server is running.

**Describe the solution you'd like**

Overly simplistic (I guess), but something like this would be nice:

```js
// index.tsx
import ReactDOM from 'react-dom/client';
import Ladle from '@ladle/react';

import App from './App';

const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement);

root.render(
	<React.StrictMode>
		<App>
			<Ladle config={/* optional config here */} />
		</App>
	</React.StrictMode>
);
```

**Describe alternatives you've considered**
Storybook doesn't have something like this, not sure if there are some other "story" libraries with the functionality I'm asking for.

**Additional context**
Nothing right now.

**Comment by tajo** [comment]
I don't really understand what you are trying to achieve.

```jsx
root.render(
	<React.StrictMode>
		<App>
			<Ladle config={/* optional config here */} />
		</App>
	</React.StrictMode>
);
```

This is not how Ladle works. The vast majority of its functionality is a custom vite plugin, vite itself and CLI. The UI is just a small piece of it.

**Comment by d-tasevski** [comment]
@tajo Sorry, I guess I wasn't clear, basically, I want to render the Ladle in the application itself. For example:

- start the application with `yarn start` which is using webpack under the hub
- application opens up in the browser
- Ladle navigation and stories are visible on the screen

Alternative would be to replace the last step from above by running the `ladle` separately. It's not a "problem", per see., but I would like, if possible, to avoid having another script running, and run the ladle directly in my app, with a webpack.

**Comment by tajo** [comment]
> run the ladle directly in my app, with a webpack.

That's not possible. Vite is a direct replacement of Webpack. And Ladle is tightly coupled with Vite. So you have to start a Vite dev server for Ladle to function.
