### ISSUE TITLE
Story sorting

### ISSUE THREAD

**Issue by joe-bell** [tajo/ladle#180]
**Is your feature request related to a problem? Please describe.**

We've just migrated our internal Storybook to Ladle and we're super happy with the results, but one thing we miss dearly is the ability to sort stories

Storybook offers the [`storySort`](https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy) option for this, and we used this previously to bring more-important stories/READMEs to the top of the navigation

**Describe the solution you'd like**

Something like a `sort` parameter in Ladle's `config.js`:

```js
export default {
  sort: {
    order: ['Intro', 'Pages', ['Home', 'Login', 'Admin'], 'Components', '*', 'WIP']
  }
};
```

Which by default would be set as:

```js
export default {
  sort: {
    method: "Alphabetical"
  }
};
```

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by tajo** [comment]
Yea, this would be a nice feature to have.
