### ISSUE TITLE
Ladle is incompatible with the RegExp format of `resolve.alias`

### ISSUE THREAD

**Issue by pdeslaur** [tajo/ladle#184]
**Describe the bug**

When the `vite.config` file contains an alias in the `Array<{ find: string | RegExp, replacement: string, customResolver?: ResolverFunction | ResolverObject }>` format, Ladle fails with the error:

```
[alias] Cannot read properties of undefined (reading 'length')
```

**Reproduction**

I only tried with React v18 - but I suspect a similar failure with React v17.

Repro: https://stackblitz.com/edit/ladle-vxskfr?file=vite.config.ts

**Root cause**

There are 2 packages in play here.

The first one is the [`@rollup/plugin-alias`](https://github.com/rollup/plugins/tree/master/packages/alias#entries) rollup plugin used by Vite. That plugin provides 2 different ways of configuring "alias". In Vite, this is exposed in the [`resolve.alias`](https://vitejs.dev/config/#resolve-alias) option.

The second one is ladle itself. When ladle manipulates `vite.config`, it uses one of the format supported by `@rollup/plugin-alias`: https://github.com/tajo/ladle/blob/master/packages/ladle/lib/cli/vite-base.js#L49. Unfortunately, when a user `vite.config` is relying on the other format, the [`mergeConfig`](https://github.com/tajo/ladle/blob/master/packages/ladle/lib/cli/merge-vite-configs.js) attempts to merge both - but it isn't aware of the nuances of each configuration option - so it doesn't merge properly and an empty object is appended to the `resolve.alias` array. This is likely due to this line: https://github.com/tajo/ladle/blob/master/packages/ladle/lib/cli/vite-base.js#L49

**Proposed fix**

Welp... There's no real magic solution here. I don't think we want ladle to be aware of all the different implementations of Vite 
configuration options. However, in this specific case, we could update the `reactAlias` hack to use the more advanced alias usage of Vite. 

Something like replacing:

https://github.com/tajo/ladle/blob/master/packages/ladle/lib/cli/vite-base.js#L49-L54

With the following (minus proper types 😅 )

```
const resolve = {}
try {
  await import("react-dom/client");
} catch (e) {
  resolve.alias = [{find: "react-dom/client", replacement: "react-dom"}];
}

// And then include resolve when building config
```

Pro:
- Doesn't touch the `alias` option at all for React v18 users

Con:
- This is a **breaking change** for React v17 users that configure `resolve.alias` with the object format. These users would have to update their `vite.config` file to use the `Array[...Object]`. 

Even with the con - I feel like this is a better solution than doing nothing since React v17 users have a clean way forward without losing any features - you "just" lose syntax sugar.

I'd love to get some feedback here - I'll be happy to draft a PR with the fix if we agree on a direction :)

**Environment**

 - OS: MacOS
 - Browser: N/A
 - Version: N/A

**Comment by tajo** [comment]
Good catch. This is annoying.

> These users would have to update their vite.config file to use the Array[...Object]

How about we first check if `resolve.alias` coming from the user is array or object and use matching version of `react-dom/client` import based on that?

**Comment by pdeslaur** [comment]
> How about we first check if `resolve.alias` coming from the user is array or object and use matching version of `react-dom/client` import based on that?

Good point - didn't consider that, but it's a more robust option. I'll send a PR and we can pick up the convo there.

Ladle is awesome btw - and that makes YOU awesome too!
