### ISSUE TITLE
Ability to return to normal mode after screen has been set to full screen

### ISSUE THREAD

**Issue by jcleefw** [tajo/ladle#185]
**Describe the bug**

When the screen puts a story into fullscreen, currently there are no way to return to the non-fullscreen mode. 

**Reproduction**

Click on fullscreen on any of the stories. There are no quick way to return to non fullscreen mode except for manually updating the URL

More about [troubleshooting](https://ladle.dev/docs/troubleshooting).

**Environment**

 - desktop
 - All Browser

**Comment by tajo** [comment]
Planning to add an opt-in iframe mode for this use-case.

**Comment by tajo** [comment]
Ah, actually I misunderstood the ask. The linked PR solves a different issue when story itself takes the fullscreen (like a modal + overlay) and won't let you click on the sidebar links.

To get back, you should just hit "go back" in your browser. The preview (fullscreen) mode is just the story without any Ladle stuff/UI.

**Comment by jcleefw** [comment]
Actually i think just go back is not a great way of UX. The current behavior is a bit confusing given that when you move to fullscreen, all the ability for navigation is now gone. 

My suggestion for fullscreen mode to open a new tab what has the story in fullscreen, keep the tab with the navigation as it is.

**Comment by tajo** [comment]
> My suggestion for fullscreen mode to open a new tab what has the story in fullscreen, keep the tab with the navigation as it is.

Hm, maybe turning it into a link like behavior when the middle (wheel) click opens it into a new tab?

**Comment by jcleefw** [comment]
yes .. it's a simple change that doesn't require too much of design, yet improve the User experience
