### ISSUE TITLE
Respect existing PostCSS config within vite config

### ISSUE THREAD

**Issue by ekatioz** [tajo/ladle#195]
**Is your feature request related to a problem? Please describe.**

As stated in the docs, if the project contains a PostCSS config, it will be applied. What I foolishly expected was that I could use `css.postcss` in the vite config to provide a PostCSS config. 😅 

Of course this is not a big problem, but it took me an hour finding out why my PostCSS plugins were working fine in vite, but not in ladle.

**Describe the solution you'd like**

Therefore I'd suggest to either add something like "Ladle doesn't support providing a PostCSS config within the vite config." to the docs or check if there's a config in `css.postcss` and only if there's not, fill it with the current working directory.

**Comment by tajo** [comment]
Yea, we should not override the user's `vite.config.js` `css.postcss` value. If not defined, we should still set it to the current working directory so it matches the expected default behavior. (Ladle's default cwd is hidden inside `node_modules`) 

As a workaround for now, you can place your settings into `./postcss.config.js` (in the project's root).
