### ISSUE TITLE
Support NX

### ISSUE THREAD

**Issue by davidbani** [tajo/ladle#213]
Documentation to support NX monorepo setup. 

Adding a target for libs/ui -> `project.json` as follows:

```
"stories": {
      "executor": "nx:run-commands",
      "options": {
        "command": "pnpm ladle serve"
      }
    }
```
and running `nx run ui:stories` runs **successfully**. 

However is unable to resolve shared dependencies. 

<img width="713" alt="Screen Shot 2022-08-04 at 1 03 51 am" src="https://user-images.githubusercontent.com/1149860/182667231-f55eb8a1-6b84-4f55-952e-cb801d5eec63.png">

Do I need to add resolve alias to config.mjs?

**Comment by tajo** [comment]
> Do I need to add resolve alias to config.mjs?

`vite.config.js` can be used to set [resolve.alias](https://vitejs.dev/config/shared-options.html#resolve-alias).

**Comment by davidbani** [comment]
Ok, this seems to work by setting up `vite.config.ts`:

```
import { defineConfig } from 'vite';
import tsconfigPaths from 'vite-tsconfig-paths';
import path from 'path';

export default defineConfig({
  plugins: [tsconfigPaths()],
  resolve: {
    alias: {
      '@project/ui': path.resolve(__dirname, './libs/ui/src/index.ts'),
    },
  },
});
```
