### ISSUE TITLE
Support for importing named packages within a yarn monorepo

### ISSUE THREAD

**Issue by paulzacz** [tajo/ladle#218]
# Setup

Use a yarn (3.2.1) monorepo.
ladle is in a separate workspace from the components that it is to render.

Within .ladle/components.tsx:
```typescript
import type { GlobalProvider } from '@ladle/react';
import { Root } from '@scope/package'

export const Provider: GlobalProvider = ({ children }) => <Root>{children}</Root>;
```
Get runtime error:
> Uncaught SyntaxError: The requested module '/static/scope__storybook/1.0.4/@fs/C:/git/@scope/package/dist/index.js' does not provide an export named 'Root' (at components.tsx:3:10)

**Comment by tajo** [comment]
Quite hard to look into this without a reproduction. We use Ladle in a monorepo setup, there is nothing that should technically prevent it.

**Comment by paulzacz** [comment]
I'll see what I can do with replication steps on Monday.

**Comment by paulzacz** [comment]
Here's a reproduction repo:

https://github.com/paulzacz/ladle-218-reproduction

I've added two commits. The first commit works, but uses relative paths in its import statement, crossing workspace boundaries. The second commit imports from the target package without using relative paths in the import statement.

**Comment by paulzacz** [comment]
Reproduction steps:

```
yarn install
yarn turbo run build
yarn workspace @scope/ladle-218-reproduction-storybook ladle:start
```
See the console.error in Chrome developer tools.

**Comment by tajo** [comment]
So the error is actually exactly describing what's happening. You are trying to import modules that `@scope/ladle-218-reproduction` doesn't expose. In other words, you need to set a proper package boundaries and ideally, you should import the source files and not the build output (which your example targets?).


Ladle (Vite) expects that you are correctly using the [package.json/exports field](https://nodejs.org/api/packages.html#exports) (or older `main` field):

Adding something like this into `@scope/ladle-218-reproduction`'s `package.json`: 

```js
  "exports": {
    ".": "./src/index.ts"
  },
```

fixes 


```js
import { Root } from '@scope/ladle-218-reproduction';
```

There is the same issue with 

```js
import '@scope/ladle-218-reproduction/dist/ladle-218-reproduction.css';
```

Again, you probably don't want to target build output (that doesn't even exist in your repo) and you need to set proper boundaries.

Alternatively, you could place Ladle into the package itself or keep using relative paths.

This is not an issue with Storybook, since Webpack doesn't really care if your `main` and `exports` are broken and happily import deep paths.

**Comment by paulzacz** [comment]
Your explanation is incomplete. I forgot to include the build command in my initial comment with the reproduction url, but added it in a follow-up reply before yours.

If you generate the build output, then the main field points to a real file and generates my original error in runtime.

I'm aware of the newer exports field, and the limitations of needing to build the target project for updates to propagate to ladle. The problem is I can't set the default export of my package to a typescript file. My actual project has JavaScript and typescript consumers. I also rely on Babel plugins to shape the output in certain ways, such as componentizing svg files to react companions.

While I can use relieve paths in the configuration of ladle, my concern is that I will be adding more intra-repository imports to my components in the future. If ladle can't use my build output in this simple case, I'm concerned that it won't be able to do so when my component imports other components from a third yarn workspace.

As I type this up, I'm beginning to think that this is less about intra-workspace imports and more to do with the fact that my build output is a commonjs module, not an esmodule. In which case, the problem may lie in vite or it's config. I'm not certain though, so any confirmation you can provide would be much appreciated.

**Comment by tajo** [comment]
> As I type this up, I'm beginning to think that this is less about intra-workspace imports and more to do with the fact that my build output is a commonjs module, not an esmodule.

Yea, Vite expects that all user code is ESM and workspaces are treated as user code.

You could explicitly list CJS workspaces through [https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-include](https://vitejs.dev/config/dep-optimization-options.html#optimizedeps-include) so Vite would pre-bundle them with esbuild (the same way how node_modules deps are treated). Personally, I would still rather import the source code directly - you can also use the `exports` field to expose both ESM and CJS versions of your package. Having explicit package boundaries is the right thing to do. It's now enforced by Node.js as well, so if you want to use ESM and do server-side rendering or run unit tests, you will need to do it at some point.  

(There is also a workaround to use a babel plugin to [transform CJS back to ESM](https://www.npmjs.com/package/babel-plugin-transform-commonjs) so Vite accepts user code CJS but that would be a ridiculous setup in your context.)

Anyway, you should be able to reproduce the same behavior just by using plain Vite, so it might make sense to search for answers / open up an issue [there](https://github.com/vitejs/vite). Ladle doesn't change anything about how this works.

**Comment by paulzacz** [comment]
Thanks for the detailed, and thoughtful reply.

Typescript only just added support for package.json exports this year, and I was able to refactor my build process to take advantage of it last Friday. I'm still a little wary about setting `"moduleResolution": "Node16"` for my whole project given that will make me subject to all the misconfigured exports for all my dependences.

Importing the source code directly is certainly the way to go for my tier 1 imports, but I can't do that if my imported component imports the CJS export from another workspace. At that point I'll either have to build both ESM + CJS or explicitly list those workplaces as CJS.

Still, that's a problem for another day.
