### ISSUE TITLE
Compatible with classic JSX transform

### ISSUE THREAD

**Issue by Hchyeria** [tajo/ladle#219]
Hi, Tajo,
I found after merging this PR #214, 
it's not working on a lower React version (for example 16.3), which still uses the [classic JSX transform,](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) and still needs to import React at the JSX file, otherwise, it will get `React is not defined` error:

![image](https://user-images.githubusercontent.com/30401991/183389642-23261bec-313f-44ac-92be-961c613eba80.png)

Can you consider supporting the lower React version (classic JSX transform)?
Thanks

**Reproduction**
https://stackblitz.com/edit/node-w2udtk?file=package.json

**Environment**

- React: 16.3.1

**Describe the solution you'd like**
Need to `import React` instead of `import type` at the JSX file and remove the `importsNotUsedAsValues: error` at config

**Comment by tajo** [comment]
This is why Ladle requires

```
"peerDependencies": {
  "react": ">=16.14.0",
  "react-dom": ">=16.14.0"
},
```

I don't see a value in supporting older versions since the upgrade for 16.x users should be pretty straightforward (and 16.14 was released 2 years ago). Also, I don't think we can have it both ways when it comes to the JSX transform.
