### ISSUE TITLE
`ladle dev` ignores default browser

### ISSUE THREAD

**Issue by fwouts** [tajo/ladle#224]
**Describe the bug**

I use Firefox as my default browser on MacOS, but `ladle dev` insists on opening Chrome.

**Reproduction**

Clone https://github.com/fwouts/hungry and run `yarn ladle` after setting your default browser to Firefox (or any other browser than Chrome I guess!) :)

**Environment**

 - OS: MacOS
 - Browser: Firefox or Chrome depending on how you phrase the question!
 - Version: 2.1.0

**Comment by iDuuck** [comment]
I think this can be solved using the [`x-default-browser`](https://www.npmjs.com/package/x-default-browser) npm package, and then fallback to Google Chrome? If this is fine for you (@tajo) I'd like to make a PR for this.

**Comment by tajo** [comment]
> I think this can be solved using the [x-default-browser](https://www.npmjs.com/package/x-default-browser) npm package, and then fallback to Google Chrome? If this is fine for you (@tajo) I'd like to make a PR for this.

It seems very outdated so it might not even work for latest OS?

We use https://www.npmjs.com/package/open and it should just use the default browser by default. We might just have some wrong logic here: https://github.com/tajo/ladle/blob/main/packages/ladle/lib/cli/open-browser.js

**Comment by iDuuck** [comment]
Yeah, what we are doing here right now is, that we are only checking for a specific list of browsers, but not what the default one is.

The problem I am seeing here, is that we are not able to check, whether the user has already opened a tab with the same URL.

Using only `open` will (afaik) not solve this either. Hence, my solution would include that we are checking the default browser with this (old) package, and then we are either running our apple script, or we are going to just use `open` to do the job.

**Comment by tim-rohrer** [comment]
I can confirm on my macOS system for which Safari is the default, Chrome is opened by `ladle serve`. 

I actually don't mind as I've been trying to get CRA to open Chrome but it won't! :-) 

I'm just sharing because the default is not what is being opened.
