### ISSUE TITLE
On stories filtering

### ISSUE THREAD

**Issue by phaistonian** [tajo/ladle#237]
`.stories` does not work as a function (too). 

That makes it tricky to filter stories based on user input.

The reason filtering is needed is because it can help focus on specific stories and because the performance and start-up time is better the fewer stories in need to be parsed.

That said:

- Either enable filtering stories based on user input _natively_.
- Or, make `.stories` support a function.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Pass the filter (pattern) like so `ladle serve [pattern]`

**Describe alternatives you've considered**
None

**Additional context**
In Storybook, I can do this sort of easily like so (since stories can be a functional):

```js
const filter = JSON.parse(process.env.npm_config_argv).original.slice(1);

module.exports = {
  stories: !filter
    ? [`../src/**/*.stories.mdx`, `../src/**/*.stories.@(js|jsx|ts|tsx)`]
    : async () => {
        const absPath = require('path').resolve(__dirname, '..', 'src');
        const pattern = `${absPath}/**/*.stories.js*`;
        const matches  = await glob(pattern);
        return matches.filter(match => match.includes(filter));
      },
   ....
```

**Comment by tajo** [comment]
What's the end goal?

You can use 

```sh
ladle serve --stories=[pattern]
```

**Comment by phaistonian** [comment]
@tajo To enable post-filtering based on stories filtered. If you have a large number of stories, that will help a lot in terms of start-up time, plus it would reduce the clutter in the list.

I guess one can do some wrapping based on the CLI input too, as you said.

**Comment by tajo** [comment]
> that will help a lot in terms of start-up time

Should not really impact Ladle that much since stories are code-splitted and loaded one by one.
