### ISSUE TITLE
Hot reload broken?

### ISSUE THREAD

**Issue by gunters63** [tajo/ladle#246]
**Describe the bug**

Hot reload does not work as expected.
I am quite sure it worked before, maybe with an earlier version?
I also started to have trouble with hot reload on my current UI project.

**Reproduction**

Click on StackBlitz Link on https://ladle.dev/ (as of Date 8/30/22). 
Edit the interior text of the Hello Component and save
Browser is not refreshed, you have to manually refresh the Stackblitz browser.
You can see in the console that Vite logs HMR messages.

""Environment**

Stackblitz Demo
Dependencies:
````
  "dependencies": {
    "@ladle/react": "^2.3.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "@types/react": "^17.0.33",
    "@types/react-dom": "^17.0.10",
    "typescript": "^4.5.4"
  },
````

**Comment by tajo** [comment]
Seems 2.2 broke HMR, looking into the fix.
