### ISSUE TITLE
TS import alias break if `vite-tsconfig-paths` is also used in `vite.config.ts`

### ISSUE THREAD

**Issue by steschwa** [tajo/ladle#265]
**Describe the bug**

As described in the documenation and [this](https://github.com/tajo/ladle/issues/59) issue, `vite-tsconfig-paths` is enabled by Ladle by default. `baseUrl` and `paths` are resolved correctly by Ladle if used. The problem is that if `vite-tsconfig-paths` is also used in `vite.config.ts` (which you obviously want because otherwise Vite is not able to resolve path aliases) Ladle fails with the following error 
![CleanShot 2022-09-26 at 16 34 35@2x](https://user-images.githubusercontent.com/24265130/192304174-8a8f3a8b-62be-4f10-b9fe-8fa38696334d.png)
 
**Reproduction**

Here's a repo to reproduce the error: https://github.com/steschwa/ladle-tsconfig-alias

Simple change `vite.config.ts` from

```typescript
import { defineConfig } from "vite"
import react from "@vitejs/plugin-react"

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [react()],
})
```

to

```typescript
import { defineConfig } from "vite"
import react from "@vitejs/plugin-react"
import tsconfigPaths from "vite-tsconfig-paths"

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [react(), tsconfigPaths()],
})
```

**Environment**

 - OS: macOS 12.6
 - Browser Chrome, Safari
 - Ladle version 2.4.3

**Comment by tajo** [comment]
Can you configure the [`root`](https://github.com/tajo/ladle/blob/main/packages/ladle/lib/cli/vite-base.js#L125) path?

That should fix it for both Ladle and your Vite application.

**Comment by steschwa** [comment]
Thanks @tajo that fixed it! Do you want me to update the documenation in case someone is facing the same issue?

For anyone else facing this issue:
If `vite-tsconfig-paths` is used in your project it's required to initialize it with the correct path to where `index.html` is located.

**vite.config.ts**
```typescript
import { cwd } from "node:process"
import tsconfigPaths from "vite-tsconfig-paths"

export default defineConfig({
  plugins: [
    tsconfigPaths({ root: cwd() }) // 👈 add path to where `index.html` is located
  ]
})
```

Both `yarn ladle serve` and `yarn dev` are now able to resolve alias imports correctly
