### ISSUE TITLE
undefined values in argTypes with an options array

### ISSUE THREAD

**Issue by apttap** [tajo/ladle#266]
**Is your feature request related to a problem? Please describe.**
I don't see a good way of using `undefined` values in options for story controls (in a `select` specifically, have not tried others).  Currently it works, but there are warnings from react for not using keys on the options lists (I suppose the key is undefined). 

**Describe the solution you'd like**
My idea was that if an array item is `undefined` then it gives it a proper key and lists 'undefined' as an option instead of a blank value.  storybookjs/storybook#13259 had a similar issue

**Describe alternatives you've considered**
there was an issue at storybookjs/storybook#13259 and [they had a resolution](https://github.com/storybookjs/storybook/issues/13259#issuecomment-841011922) on it, I tried the methods listed there to no avail.

**Additional context**
![dev console](https://user-images.githubusercontent.com/566627/192782027-c4a5d7b1-5684-4b0d-b1ac-3e5e11d4c05d.png)

**Comment by tajo** [comment]
I think we just need to fix the `undefined` as a React key.

**Comment by apttap** [comment]
I did work on this, corrected the console errors. There remains an issue with displaying the `undefined` value for radio button options in the example. Not ready for a PR. I will continue improve solution if no one else is working on it.

[See diff](https://github.com/tajo/ladle/compare/main...apttap:ladle:controls_undefined)

**Comment by apttap** [comment]
I created a PR that resolves this bug

https://github.com/tajo/ladle/pull/305#issue-1522916869

**Comment by tajo** [comment]
More robust fix https://github.com/tajo/ladle/pull/315

**Comment by pReya** [comment]
@tajo You said you commited a robust fix, however I don't quite understand how I can make a select/radio prop undefined by user choice?

When I add undefined to my options, e.g.
```
VerticalNewsCardStory.argTypes = {
  variant: {
    options: ["dark", "light", undefined],
    control: { type: "radio" },
    defaultValue: "dark",
  },
};
```

The prop will always be of type string (e.g. I get `"undefined"` instead of `undefined`). Is this intended?
