### ISSUE TITLE
Adding emotion causes breaking errors

### ISSUE THREAD

**Issue by tuckwilli** [tajo/ladle#268]
**Describe the bug**

Adding [emotion ](https://emotion.sh/docs/introduction)to a ladle project causes the following breaking errors:
```
// firefox errors
Uncaught SyntaxError: ambiguous indirect export: default [emotion-react-_isolated-hnrs.browser.esm.js:1:7](https://ladle-s1xwcp--4123.local-corp.webcontainer.io/@fs/home/projects/ladle-s1xwcp/node_modules/@emotion/react/_isolated-hnrs/dist/emotion-react-_isolated-hnrs.browser.esm.js?v=cf4a87f3)
Uncaught Error: Module function declarations have already been instantiated

// chrome error
Uncaught SyntaxError: The requested module '/@fs/home/projects/ladle-s1xwcp/node_modules/hoist-non-react-statics/dist/hoist-non-react-statics.cjs.js?v=4d5c81db' does not provide an export named 'default' (at emotion-react-_isolated-hnrs.browser.esm.js?v=4d5c81db:1:8)
```

This does not happen in a standard vite project.

**Reproduction**

Reproduction of error can be found here: https://stackblitz.com/edit/ladle-s1xwcp?file=vite.config.ts
The same vite config can be seen not erroring in a fork of https://vite.new/react-ts here: https://stackblitz.com/edit/vitejs-vite-pszpec?file=vite.config.ts
The vite config was take from [this vite starter](https://github.com/fabgrel10/vite-react-starter).

**Environment**

Replicated on windows and mac in multiple versions of chrome and firefox.

**Comment by soulsam480** [comment]
Same is happening to me, it doesn't seem to recognise the Provider export. Any workarounds for it @tajo ? We're evaluating ladle for our huge storybook package. thx 🙏🏽

**Comment by soulsam480** [comment]
any direction on what might be causing the issue ? I can help fixing the issue 🙏🏽

**Comment by tajo** [comment]
This `vite.config.js`: 

```js
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
  optimizeDeps: {
    include: ['hoist-non-react-statics'],
  },
  plugins: [
    react({
      jsxImportSource: '@emotion/react',
      babel: {
        plugins: ['@emotion/babel-plugin'],
      },
    }),
  ],
});
```

https://stackblitz.com/edit/ladle-hb1qmg?file=vite.config.ts

For some reason, `hoist-non-react-statics` doesn't get pre-cached/converted to ESM by default. Not really sure why.

**Comment by soulsam480** [comment]
Thx for the reply. I also don't know much about these. Let me try this workaround 🙏🏽
