### ISSUE TITLE
ladle's vite cache conflicts with node_modules/.vite

### ISSUE THREAD

**Issue by blahbleepew** [tajo/ladle#269]
If you run ladle at the same time as another vite project, by default they both share the same cache which causes confusing bugs. the default value for the cacheDir should be set to node_modules/.ladle or something

**Comment by tajo** [comment]
Does it break the application? They should both share the same dep versions. 

Anyway, you can change the cache dir through the configuration but if this is an universal problem, we should set a different default dir.

**Comment by blahbleepew** [comment]
it did break things when I tried it and I did have to set a different cachedir
