### ISSUE TITLE
Can you publish vite-plugin as a separate package?

### ISSUE THREAD

**Issue by blahbleepew** [tajo/ladle#270]
Title. I constantly have problems with UI component managers being finicky with my build setups and what finally solved my problems was just using your vite-plugin directly.

**Comment by tajo** [comment]
> constantly have problems with UI component managers being finicky with my build setups

Can you elaborate?

> using your vite-plugin directly

You mean the plugin that creates virtual module that exports stories?

**Comment by blahbleepew** [comment]
>Can you elaborate?
I tend to add new things that end up breaking my storybooks/cosmos/ladle etc. for cosmos it was esmodules, storybook it was yarn pnp + other stuff. ladle didn't like me doing SSR, I was using ssr + relay + use-relay-mock + linguijs

example starter: https://github.com/brillout/vite-plugin-ssr/tree/main/examples/react-full

>You mean the plugin that creates virtual module that exports stories?
yes it's very nice

**Comment by tajo** [comment]
> > You mean the plugin that creates virtual module that exports stories?

> yes it's very nice

Maybe later once we have MDX support. Also, it would probably not follow semver.
