### ISSUE TITLE
getting errors about exported interfaces

### ISSUE THREAD

**Issue by chadlavi-casebook** [tajo/ladle#271]
**Describe the bug**

I have a typescript file (`address.ts`) that includes an exported interface (`AddressProps`). That interface is used elsewhere -- but the ladle app crashes on an uncaught syntax error when I try to start it, with an error message like

```
Uncaught SyntaxError: The requested module '/@fs/Users/MyUser/Dev/my-app/src/components/helpers/address.ts' does not provide an export named 'AddressProps'
```

I suspect this has something to do with how ladle is processing typescript? I went in the browser and looked at the code in the dev app, and it is indeed true that the `address.ts` file in at `/@fs/Users/MyUser/Dev/my-app/src/components/helpers/address.ts` has the declared export of the interface stripped out of it:

<img width="1392" alt="Screen Shot 2022-10-03 at 13 54 09" src="https://user-images.githubusercontent.com/45078010/193645687-9cec35a4-0d1f-48e2-be34-e51c40e9b559.png">

here's the start of the source file for reference: 
<img width="680" alt="image" src="https://user-images.githubusercontent.com/45078010/193645797-086e7e91-8908-41d4-a527-ac5aefb8ce26.png">

**Reproduction**

I am unable to reproduce this in a [a ladle sandbox](https://stackblitz.com/edit/ladle-ahjtez?file=src%2Fbasic.stories.tsx,src%2Faddress.ts), but this issue does not happen when I run storybook in the same codebase, and does not affect my published component library. 

**Environment**

- OS: macOS 12.6
- Browser Chrome 106.0.5249.61 (Official Build) (x86_64)

**Comment by tajo** [comment]
Hey, can you create a github repo as a repro?
