### ISSUE TITLE
Increase `z-index` of the `ladle-addons` menu

### ISSUE THREAD

**Issue by bruceharrison1984** [tajo/ladle#272]
**Describe the bug**
Any z-index larger than 1 on a story threatens to overlap the ladle-addons menu, rendering the buttons unusable.

**Reproduction**
Create a story that fills the entire viewport, and give it a z-index greater than 1. Now you can't click the buttons anymore.

Ideally, the z-index would be high enough that the menu would never conceivably be covered.

**Comment by tajo** [comment]
We can increase zIndex. You can also use "iframed" mode https://ladle.dev/docs/width#iframe - that will ensure that the Ladle's UI stays in front.
