### ISSUE TITLE
Triggering an action seems to force the whole story to remount and lose state

### ISSUE THREAD

**Issue by dsalisbury** [tajo/ladle#273]
**Describe the bug**

Triggering an action seems to force the whole story to remount and lose any state. Is this intended?

**Reproduction**

I made this stackblitz with two stories, one that has actions via argtypes and one which uses the `action()` import: https://stackblitz.com/edit/ladle-al8wrx?file=src%2Fbasic.stories.tsx

Both exhibit the same behaviour of remounting the story when an action is triggered.

There's a story control to change whether or not the action is triggered when clicking the button. What I'm seeing is that if the action is triggered, the story remounts and the counter stays at zero, but if the action is not triggered, the counter increases as one would expect.

**Environment**

- OS: Arch Linux
- Browser: Firefox 105.0.2 (64-bit), Chromium 106.0.5249.91 (Official Build) Arch Linux (64-bit)
- Version
  - @ladle/react 2.4.3
  - react 16 and 18

**Comment by tajo** [comment]
Yea, this is not a good behavior.
