### ISSUE TITLE
Consider simplifying type exports and require moduleResolution: bundler

### ISSUE THREAD

**Issue by gunters63** [tajo/ladle#280]
**Describe the bug**

(Some) Ladle Types cannot be resolved correctly with Node16 resolution

**Reproduction**

-  pnpm create vite my-react-app --template react-ts
- pnpm i
- Add a story using a decorator, the example from the website is sufficient:
````
import type { Story, StoryDecorator } from "@ladle/react";

export default {
  decorators: [
    (Component, context) => (
      <div style={{ margin: "3em" }}>
        {context.globalState.control.label.value}
        <Component />
      </div>
    ),
  ] as StoryDecorator[],
};

const Card: Story<{
  label: string;
}> = ({ label }) => <p>Label: {label}</p>;

Card.args = {
  label: "Hello",
};
````

- pnpm tsc --noemit shows no errors:
- Change node resolution to Node16 in tsconfig.json
- pnpm tsc --noemit shows now errors:

<img width="436" alt="image" src="https://user-images.githubusercontent.com/90346/195847333-0c1078b8-3db5-421a-8ed6-f5d79c33014d.png">

**Comment by gunters63** [comment]
I am quite sure this was introduced with the fix for https://github.com/tajo/ladle/issues/267

**Comment by gunters63** [comment]
The package.json exports looks odd now, with a "default" entry pointing to a .ts file and types pointing to .d.ts files containing  a copy of all types. Maybe the Typescipt compiler gets confused by this.

Interestingly, if i delete the types entry in Ladles packages.json exports Typescript complains about missing .js extensions in the ladle dist sources. When I add them everything works as expected. I can even switch back to the default node resolution.

**Comment by tajo** [comment]
I can reproduce this too. 

> Interestingly, if i delete the types entry in Ladles packages.json exports Typescript complains about missing .js extensions in the ladle dist sources. When I add them everything works as expected. I can even switch back to the default node resolution.

That's expected and the reason why for the recent changes.

@frehner Any idea how to fix this?

**Comment by gunters63** [comment]
I still think a cleaner approach would be to convert Ladle to use Node16 (which should also work for projects using Ladle which still use the old Node resolution). This would also require to tsc-compile the Ladle sources to a dist folder (.js files and type declaration files). Then the package,json exports could use the standard approach of exporting exports.js and exports.d.ts from the dist folder.

I am using this approach in my Monorepo where the web application importing packages built this way is using Vite. This works without a problem, Vite is just using the .js files from the packages without recompiling them.

I tried to convert Ladle to Node16 resolution but ran into some issues (Vite Plugin-React and Vite TsConfig-Paths, which do not play well with Node16 resolution and two strange type errors in get-story-imports and get-story-list), but I am sure these can be resolved. Maybe I can solve them and make a merge request.

**Comment by gunters63** [comment]
I could try to make a merge request using this approach.

**Comment by frehner** [comment]
> I can reproduce this too.
> 
> > Interestingly, if i delete the types entry in Ladles packages.json exports Typescript complains about missing .js extensions in the ladle dist sources. When I add them everything works as expected. I can even switch back to the default node resolution.
> 
> That's expected and the reason why for the recent changes.
> 
> @frehner Any idea how to fix this?

The TLDR is that because the source code isn't using file extensions in import paths, and `NodeNext`/`Node16` are strict about explicitly using file extensions, then TS can't find the file. 

For example, in the reproduction above, you'll note that `Story` is found:
![Screen Shot 2022-10-17 at 10 25 32 AM](https://user-images.githubusercontent.com/3054066/196231397-db92835b-6c66-48c8-b644-646de74bfd21.png)

That's because `Story` is part of the main file that we point directly to in package.json. However, `StoryDecorator` isn't found - and that's because the import statement `../shared/types` doesn't have a file extension on it, so technically NodeNext TS can't find that file. 

![Screen Shot 2022-10-17 at 10 27 00 AM](https://user-images.githubusercontent.com/3054066/196231691-ca770d25-0ad8-45b0-ac27-196af732cb9e.png)

So yeah. That's why. ☹️ 

How to fix it would potentially mean adding file extensions to all of your import statements. Or maybe seeing what @gunters63 output looks like and seeing what happens there. 

-----

During this, I also found an issue with my previous PR that I needed to fix. PR coming shortly.

**Comment by gunters63** [comment]
Adding file extensions and not using Node16 resolution seems risky. It would be easy to forget an extension (when adding/changing code) and tsc would not complain. 

Btw, I tried to convert Ladle to Node16 resolution (gave it about 1 hour time) but ran into strange problems with the vite react and the vite tsconfig plugins which do not play well with Node16 resolution yet and also had two type errors with some code consuming AST structures which i couldn't fix.

I think the safest route is just to do it the standard way, let the package exports point to .(c)js and .d.ts files which means adding a tsc transpile step and deploy the .js and .d.ts files with other needed assets to a dist folder.

**Comment by frehner** [comment]
>Adding file extensions and not using Node16 resolution seems risky. It would be easy to forget an extension (when adding/changing code) and tsc would not complain.

There are lint rules for it, if that's any consolation. https://github.com/import-js/eslint-plugin-import#importextensions

But yeah, this is annoying. There is some movement on TS's side of things to make this better, but it won't be out for a bit I suspect.

**Comment by tajo** [comment]
> There is some movement on TS's side of things to make this better, but it won't be out for a bit I suspect.

How about this https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#moduleresolution-bundler?

**Comment by gunters63** [comment]
> > There is some movement on TS's side of things to make this better, but it won't be out for a bit I suspect.
> 
> How about this https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#moduleresolution-bundler?

That could be indeed the solution, lets see when Typescript 5 releases in March :)

**Comment by frehner** [comment]
> > There is some movement on TS's side of things to make this better, but it won't be out for a bit I suspect.
> 
> How about this https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#moduleresolution-bundler?

Yup that's the one!

**Comment by tajo** [comment]
So what's the best possible setup for us? Planning to release v3 and we could just drop support for typescript v4 and older.

**Comment by gunters63** [comment]
We migrated our Monorepo to TS 5.x and moduleResolution bundler since April and never looked back. moduleResolution bundler fixed many Problems, not only this specific one. 

v3 would still support Typescript v4, just not moduleResolution Node16 (which only existed since 4.7 anyways). This was used only rarely and I think most projects migrated to moduleResolution bundler in the meantime. And even then you could just live with some typescript error suppressions.

**Comment by tajo** [comment]
I'm going to revert to the previous (simpler) setup and require projects to use `moduleResolution: 'bundler'` in v3.
