### ISSUE TITLE
Play Function

### ISSUE THREAD

**Issue by jamiebuilds** [tajo/ladle#284]
Storybooks has this ["play function"](https://storybook.js.org/docs/react/writing-stories/play-function#gatsby-focus-wrapper) feature for writing inline tests for interactions.

Migrating to Ladle would require porting all the tests you've written with these functions to something new.

Instead it would be great if Ladle supported these by default.

Even better if it could be done better than storybook by running these tests in the background in an iframe or even a background process or something like that and not affect the window you're interacting with unless you choose to play the test manually.

**Comment by tajo** [comment]
Yea, I've been thinking a lot about this feature. 

Internally, we have these `foo.stories.test.js` files that map stories into "play" functions. Also our play functions get `expect` and `snapshot` as params. The point is, we run this in our CI as a robust test suite and you can also run it locally in terminal. We built this before play functions were a thing.

I really like the idea of having this baked into the UI so it's easier to develop/debug/test but also want to preserve the "CI test suite" part that allows to do multiple assertions before/during/after the play function. 

> Even better if it could be done better than storybook by running these tests in the background in an iframe or even a background process or something like that and not affect the window you're interacting with unless you choose to play the test manually.

💯

**Comment by jamiebuilds** [comment]
I do think if you press "play" in the UI it should probably run it in the frame you see so that you can inspect it.

**Comment by tajo** [comment]
Probably not gonna support this type of "testing", it would be a lot to maintain. On the other hand if there is anything to make the integration with playwright and its test runner easier, always happy to support that.
