### ISSUE TITLE
useLocation from NPM package throws

### ISSUE THREAD

**Issue by penge** [tajo/ladle#286]
**Describe the bug**

Having a React component imported from an NPM package. This component relies on `react-router-dom` as peer dependency and uses `useLocation` hook. Creating a Story in Ladle for this imported component. Adding a router decorator for this Story. Story works during development (`$ npx ladle serve`) but does not work in the build (`$ npx ladle build && npx ladle preview`) where its component is called 4x and then it throws an error (something like useLocation calls invariant which produces error).

**Reproduction**

See https://stackblitz.com/edit/ladle-ehqexx. It will build NPM package. It will provide 4 examples, where example 3 and 4 are from the NPM package. All 4 examples work during development (`$ npx ladle serve`) but example 4 won't work during build (`$ npx ladle build && npx ladle preview`).

There are these 2 scripts to choose from:

```
all-examples-work
example4-wont-work  (run by default, modify startCommand to change it)
```

Every example component prints a message to the console. When you open Example4 during `example4-wont-work` script, it will print a message 4x and then throw.

**Comment by tajo** [comment]
This happens because you have two instances of `react-router` in your setup. You can force Vite to resolve to a single one by creating following `vite.config.js`:

```js
import { createRequire } from 'module';

const require = createRequire(import.meta.url);

export default {
  resolve: {
    alias: {
      'react-router': require.resolve('react-router'),
    },
  },
};

```

working example: https://stackblitz.com/edit/ladle-jktynv?file=vite.config.js
