### ISSUE TITLE
Exporting component directly from 

### ISSUE THREAD

**Issue by scarf005** [tajo/ladle#287]
**Describe the bug**

```ts
// hello.ts
export const Hello = () => <div>Hello</div>
```
It's not possible to do this
```ts
// hello.stories.ts
export { Hello } from './hello'
```

so this way must be used, which is inconvenient.
```ts
// hello.stories.ts
import { Hello } from './hello'

export const HelloStory = Hello
```

**Reproduction**

https://stackblitz.com/edit/ladle-z2rbi8?file=src/hello.stories.tsx

**Environment**

- OS: Ubuntu 22.04
- Browser: firefox
- Version: 107.0b9

**Comment by tajo** [comment]
We use AST based lookup when discovering stories. We could identify this syntax

```js
export { Hello } from './hello'
```

as a story.

**Comment by tajo** [comment]
Actually a bit difficult since we would have to parse/analyze the source files as well in case you are reexporting other things than React components.
