### ISSUE TITLE
how to use `react-router-dom` alongside ladle

### ISSUE THREAD

**Issue by scarf005** [tajo/ladle#289]
```ts
import { Link } from 'react-router-dom'
import { Button } from '@mantine/core'

export const TryLogin = () => (
    <Link to='/auth/login'>
      <Button variant='default'>login</Button>
    </Link>
)
```
I'm trying to render this prop into ladle, however it fails because it requires react router context.
```ts
// router.tsx
export const router = createBrowserRouter([
  {
    path: '/auth/login',
    element: <LoginPanel />,
  },
])
```
```ts
// App.tsx
import { RouterProvider } from 'react-router-dom'
import { router } from './router'

export const App = () => {
  return <RouterProvider router={router} />
}
```

I've read https://ladle.dev/docs/providers but was unable to figure out how to provide context for every elements. any help would be appreciated.

**Comment by tajo** [comment]
It's this: https://ladle.dev/docs/providers

You need to create `.ladle/components.tsx` and export/define `Provider`.

**Comment by scarf005** [comment]
> I've read [ladle.dev/docs/providers](https://ladle.dev/docs/providers) but was unable to figure out how to provide context for every elements.

to clarify more, I'm getting difficulties on how to put `RouterProvider` into `Provider`. I've blindly tried
```ts
import type { GlobalProvider } from '@ladle/react'
import { RouterProvider } from 'react-router-dom'
import { router } from 'router'

export const Provider: GlobalProvider = ({ children, globalState }) => (
  <RouterProvider router={router} />
)
```
but it doesn't seems to work.

**Comment by tajo** [comment]
You are not returning `children` aka the story itself.
