### ISSUE TITLE
Playwright recipe for automatically starting ladle preview with webServer 

### ISSUE THREAD

**Issue by thangngoc89** [tajo/ladle#293]
First of all, thank you for making ladle. Using it was a seamless experience, especially in projects that already use vite and vitest.

**Is your feature request related to a problem? Please describe.**
Since 1.11.0, playwright has a feature where you can tell it to start and wait for a local server before testing.
However, example on doing [visual snapshots](https://ladle.dev/docs/visual-snapshots) bypasses this feature.

**Describe the solution you'd like**
I've written a different code sample on how to do it using **serial** mode. Here are the steps:

1. Add this to `playwright.config.ts` 

```
webServer: {
    // This command calls 
    // ladle preview -p 61000
    command: "npm run ci:ladle",
    port: 61000,
},
```

```ts
// snapshots.spec.ts
import { test, expect } from "@playwright/test";

test.describe.serial("Laddle Visual Testing", () => {
  let stories;
  const url = "http://localhost:61000";
  test("Setup", async ({ page, request }) => {
    // fetch Ladle's meta file
    // https://ladle.dev/docs/meta
    const response = await request.get(`${url}/meta.json`);
    // iterate through stories
    const json = await response.json();

    stories = json.stories;
  });

  test("Main test", async ({ page }) => {
    for (let storyKey in stories) {
      await test.step(`${storyKey} - compare snapshots`, async () => {
        // navigate to the story
        await page.goto(`${url}/?story=${storyKey}&mode=preview`);
        // stories are code-splitted, wait for them to be loaded
        await page.waitForSelector("[data-storyloaded]");
        // take a screenshot and compare it with the baseline
        await expect(page).toHaveScreenshot(`${storyKey}.png`);
      });
    }
  });
});
```

**Describe alternatives you've considered**
Admittedly I could start the server myself some other ways as the number of tests exploded but for now, I believe this is sufficient for my use case.

**Additional context**

**Comment by tajo** [comment]
Oh cool, happy to simplify the setup. Would you update the code examples and the docs/blog using your solution?

**Comment by thangngoc89** [comment]
@tajo Please keep in mind this approach forces playwright to capture screenshots sequentially. One by one. I would love to have something that makes it easier to do both but seems like there are no other ways

**Comment by tajo** [comment]
> forces playwright to capture screenshots sequentially

Yea, that's a big downside.
