### ISSUE TITLE
CSS Reset

### ISSUE THREAD

**Issue by melMass** [tajo/ladle#304]
**Is your feature request related to a problem? Please describe.**
Ladle styling interfere with the components

**Describe the solution you'd like**
A way to completely remove default styling

**Comment by tajo** [comment]
Can you be more specific what styles are clashing?

[Iframe](https://ladle.dev/docs/width#iframe) mode could also help.

**Comment by melMass** [comment]
I will need to re-look into it later today or tomorrow, but from memory, Ladle uses `data-theme` with the same names as my project ("dark" & "light") and the main area isn't style reseted for this reason I think. 

I'm not using the theme addon switcher, but a component from my project that I wrap around all stories, but ultimately I believe they do the same thing, *i.e* set `data-theme` on body.

I will be more specific later on if needed

**Comment by tajo** [comment]
We should probably prefix those, e.g. `data-ladle-theme`.

**Comment by melMass** [comment]
That would be great indeed!
I'm going to need paddle again later today so I will be able to provide more info, try to patch it with your prefix idea and see if it's solves it.
If it does I'll PR the change
