### ISSUE TITLE
Automatically link to first story in navigation

### ISSUE THREAD

**Issue by justb3a** [tajo/ladle#311]
It would be great if clicking on a main navigation item would automatically open the first story (link to the first sibling) and not just expand the navigation item.

## Example

```
Accordion
├── Controlled
├── Disabled
└── Expanded
Button
├── Circle
└── Colors
Card
├── Image
└── Text Only
```

* Clicking on **Accordion** should automatically select and display **Controlled** (*ladle/?story=accordion--controlled*)
* Clicking on **Button** should automatically select and display **Circle**
* Clicking on **Card** should automatically select and display **Image**

## Why
It saves you one click 🙃 I am always irritated that I have to click twice to get to the first story.

Thank you 🙏

**Comment by tajo** [comment]
I like this.

**Comment by tajo** [comment]
Actually I don't like it. It gets messy to use and implement due to deeply nested items. Also, it doesn't seem to be a pattern in other apps (Storybook, Notion...).
