### ISSUE TITLE
Setting large viewport in a small browser window causes iframe to shrink and doesn't produce scrollbars

### ISSUE THREAD

**Issue by wojtekmaj** [tajo/ladle#314]
**Describe the bug**

Setting large viewport in a small browser window doesn't produce scrollbars.

**Reproduction**

* Choose story viewport: large (1024px)
* Make your browser window small enough, e.g. 800px
* Observe how the viewport you selected shrinks

**How to fix**
 
* Make sure to set min-width equal to `width` on the iframe to prevent it from shrinking when placed in a smaller viewport
* Change `.ladle-main` styles not to center the iframe when it doesn't fit inside; currently `display: flex;
    justify-content: center;` causes the iframe to be partially hidden even with the fix mentioned above applied. Instead, center the iframe using `margin: 64px auto` set on the iframe.

**Comment by amaroyche** [comment]
### Here is a video that explains desired outcome: 
Basically if we set story viewport to some value e.g 1024px it could be argued that scrollbars should be added to enable observing component behavior on larger screens (while using smaller screen).

https://user-images.githubusercontent.com/3295702/217247013-4714b5fa-c337-4a93-b1d6-425afdd872e1.mp4

currently the horizontal scrollbar is not visible and frame is fully responsive.
