### ISSUE TITLE
Are stories meant to remount every time arguments updated via controls?

### ISSUE THREAD

**Issue by some-dudes-work-account** [tajo/ladle#323]
Currently component gets remounted every time I change anything via controls so it starts from a clean slate every time. 

If a component supposed to transition smoothly when one of the props changes this behavior can't be observed in Ladle because of this. 

Tried removing custom global provider, it still does that. Observed this on `@ladle/react@2.4.5`

**Comment by tajo** [comment]
Most likely duplicate to https://github.com/tajo/ladle/issues/297
