### ISSUE TITLE
Update docs to state .ladle directory can no longer be at the project root

### ISSUE THREAD

**Issue by dtgreene** [tajo/ladle#329]
**Is your feature request related to a problem? Please describe.**
I feel like the [recent PR that restricted file access to the project root](https://github.com/tajo/ladle/pull/324) makes the docs a little misleading about where to put the `.ladle/` configuration.  They currently mention a `.ladle/config.mjs` which to me reads like your project might have the following structure:

```
|- .ladle/
| |- config.mjs
| |- components.tsx
|- src/
```

But with the new changes, this causes Ladle to break due to Vite not finding the configuration:

```
Failed to load url /@fs/project-directory/.ladle/config.mjs (resolved id: /project-directory/.ladle/config.mjs). Does the file exist?
The request url "/project-directory/.ladle/config.mjs" is outside of Vite serving allow list.
``` 

**Describe the solution you'd like**
Mention the file restriction in the docs or specify that something like `src/.ladle/config.mjs` would be more appropriate.

**Comment by tajo** [comment]
Related to https://github.com/tajo/ladle/pull/326

Do you also use custom [`base`](https://vitejs.dev/config/shared-options.html#base)?

Our intention is to make `.ladle/` work at root.

**Comment by dtgreene** [comment]
Yes this is the configuration we are using that worked prior:
```javascript
export default {
  outDir: '/build/components',
  base: '/components/',
}
```
Our setup builds Ladle and serves it alongside the normal app at `/components`.  But the `.ladle/` at the root does work if there's no `base`

**Comment by tajo** [comment]
Cool, will fix.
