### ISSUE TITLE
Range slider control

### ISSUE THREAD

**Issue by smajl** [tajo/ladle#337]
**Is your feature request related to a problem? Please describe.**
The range slider control is extremely useful for very fast testing of any content/prop which tends to have a big discrepancy in length - we usually bind it as an input to some fake data generator. It is also a blocker for "Ladle is a drop-in alternative to Storybook" since it makes all the stories using Storybook's "range" control unusable in ladle.

**Describe the solution you'd like**
Support for "range" control. Min, max, and step settings. Nothing fancy, just binding it to a standard HTML input.

**Describe alternatives you've considered**
I don't think there's an alternative. Well, primitive number input, but that's UX hell for this use case.

**Additional context**
Is this maybe on a roadmap? Or would be a PR preferred?

**Comment by tajo** [comment]
Agreed. Working on other stuff right now, PR would be great!

**Comment by smajl** [comment]
@tajo OK, I'll work on it (should have some time over the weekend). Quickly scanning the code - I also noticed - that there's a discrepancy between how SB defines options for select controls:
```
argTypes: { age: { control: 'select', options: [20, 30, 40, 50] }}
```
and what format you expect in ladle:
```
argTypes: { age: { control: 'select' }, options: [20, 30, 40, 50] }
```
This leads to "no select options provided" in ladle when you try to load SB story in it.

I'd propose to fix it along the way, so the final code tries to load options, min, max, and step settings from the `control` object. Actually no - that is a breaking change... So I'll leave the `options` as is (but shout if you want to "fix" it as well), but will put min/max/step inside the `control` where I think they belong.

**Comment by smajl** [comment]
It was actually fun&easy so here it is: https://github.com/tajo/ladle/pull/342

**Comment by tajo** [comment]
>  I also noticed - that there's a discrepancy between how SB defines options for select controls:


Ladle expects:

```tsx
argTypes = {
  size: {
    options: ["small", "medium", "big", "huuuuge"],
    control: { type: "select" },
  },
}
```

and that should be identical to https://storybook.js.org/docs/react/essentials/controls

Although we don't support top-level `control: "select"` without the type. This could be an enhancement to improve compatibility. 

Closing this issue since resolved.

**Comment by smajl** [comment]
@tajo You are correct (nothing wrong with the select config in ladle), my bad, we had the `select` config wrong in a few places in our codebase and that confused me. At least I could fix that, thanks. 😆
