### ISSUE TITLE
'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.ts(2686)

### ISSUE THREAD

**Issue by twiddler** [tajo/ladle#338]
**Describe the bug**

In `.ladle/components.tsx`, TypeScript complains about `React` if it's not explicitely imported:

> 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.ts(2686)

**Reproduction**

1. Create a new project with `npm create vite`
2. Create `.ladle/components.tsx` as shown in https://ladle.dev/docs/providers.
3. Open `.ladle/components.tsx` in VS Code.

JSX will now be underlined with the TypeScript error above.

**How to fix**

There's two ways to make this error go away:

1. Add `import React from 'react'` to `.ladle/components.tsx`.
2. Add `.ladle/components.tsx` to `tsconfig.json`'s include:
```json
{
  // ... all the other stuff ...

  "include": ["src", ".ladle/components.tsx"],
}
```

We might want to point this out in the docs.

**Comment by tajo** [comment]
Yea, seems like a documentation issue.
