### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by amaroyche** [tajo/ladle#339]
**Describe the bug**

For version v2.5.3
Switching from one story (with default values changed) to another story breaks the page. 

**Reproduction**

https://stackblitz.com/edit/ladle-hypf3x
- Go to story "Controls" and change some default values with control. (e.g switch variant to "secondary")
- Observe the control parameter in url bar:  `?arg-r-variant=secondary&story=controls`
- Now try to change story to "Controls2" and observe page break.

**Comment by tajo** [comment]
Thanks for the report. Fix release as `2.5.4`.
