### ISSUE TITLE
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

### ISSUE THREAD

**Issue by amaroyche** [tajo/ladle#357]
**Describe the bug**

in v2.6.3 there was a change in how `config.mjs` is loaded (`packages/ladle/lib/cli/vite-plugin/generate/get-config-import.js`).
In particular, on Windows OS we need to convert path to file url using `pathToFileURL` from node's `url`

instead of 
`const config = (await import(configPath).default;`

use
```
import { pathToFileURL } from 'url';
...

const config = (await import(pathToFileURL(configPath).href)).default;
```
Some reference issue and solution:
https://github.com/nodejs/node/issues/31710#issuecomment-1097798710

**Environment**

- OS: Win32

**Comment by AddictArts** [comment]
I am having this issue and this was semantically versioned as a bug fix, but broke all the stories. This is also of no help
`More info: https://ladle.dev/docs/stories#limitations`.

**Comment by AddictArts** [comment]
@amaroyche Thank you for solving this, I wasn't sure what had happened and changed. Saved me debugging it. I monkey patched the file in `node_modules`.

```js
import fs from "fs";
import path from "path";
import { pathToFileURL } from 'url';

/**
 * @param {string} configFolder
 */
const getConfigImport = async (configFolder) => {
  const configPath = path.join(configFolder, "config.mjs");
  const configExists = fs.existsSync(configPath);
  let configCode = `export let config = {};\n`;
  if (configExists) {
    const config = (await import(pathToFileURL(configPath).href)).default;
```

**Comment by AddictArts** [comment]
Also, passing `--config` on the cli doesn't seem to help or work, at least on Windows.

Issue is also Win64
