### ISSUE TITLE
useLadleContext() does not return context

### ISSUE THREAD

**Issue by amaroyche** [tajo/ladle#365]
**Describe the bug**

Docs mentioned that getting the context is experimental (https://ladle.dev/docs/providers#ladle-context),
In any case, it seems that v2.7.0 introduces a bug when trying to obtain a context.

**Reproduction**

https://stackblitz.com/edit/ladle-nzvggb?file=src%2Fbasic.stories.tsx

**Comment by tajo** [comment]
It's probably [this change](https://github.com/tajo/ladle/commit/54832e4d07e9e06dcfa4a63710a270944b7a7a00#diff-2f1799ee73eec70459c54fa51ce687a2c87f5b24e20ebc618a739985d0d0fcceL104).

**Comment by AddictArts** [comment]
+1

I like ladle, but these minor revisions or patch releases breaking everything are frustrating. The release notes also don't mention breaking changes.

**Comment by tajo** [comment]
fixed in `2.7.1`

**Comment by AddictArts** [comment]
Thanks for the quick fix and turnaround
