### ISSUE TITLE
`.defaultStory` should default to last opened story 

### ISSUE THREAD

**Issue by phaistonian** [tajo/ladle#384]
**Is your feature request related to a problem? Please describe.**

9 times out of 10, you need to figure out what the story you were working on before is and go back there.

**Describe the solution you'd like**

`.defaultStory` should point to the last opened story.

**Describe alternatives you've considered**

Come up with a script that will point to point to the last registered story using `.defaultStory`.

This would also require registering the last story - perhaps with a decorator.

**Additional context**

**Comment by tajo** [comment]
The last story could be stored in `localStorage`. It would make sense to have a new setting for this (separate from `defaultStory`). 

Personally, I don't really feel this issue that much since when using macOS + Chrome, Ladle is re-using existing tabs (including the selected story) and I typically keep my working instance open for days.

**Comment by phaistonian** [comment]
@tajo When you are switching context often or working on multiple repos, then keeping a tab pinned with Ladle makes little sense. 

The "problem" with storing the last story in localStorage is that you need this to expose server-side (node). So, a decorator should most probably make an HTTP request to an endppoint to update a file or something to be fetched when launching the service.

So it's either that, or you natively support it without the hassle ;)

**Comment by tajo** [comment]
> you need this to expose server-side (node)

Why do you need to persist this information server-side?

**Comment by phaistonian** [comment]
Well, I guess because you need to point to the stored reference upon starting the node app?

You can, of course redirect upon mounting, but that's a bit dirty — I guess.
