### ISSUE TITLE
Context for story-level decorators does not update when a change occurs 

### ISSUE THREAD

**Issue by zackheil** [tajo/ladle#386]
**Describe the bug**

I noticed when playing around with the decorators for individual stories that my own theme provider, that was depending on `context.globalState.theme`, never swapped themes when pressing the theme toggle button. This is a behavior that I didn't have when using the global decorator. After doing some experimenting, I found that the context for the story decorator doesn't actually update when the context changes.

**Reproduction**

[Here](https://stackblitz.com/edit/ladle-xvkaqk?file=src/basic.stories.tsx) is a reproduction of the issue. Notice the variable called out in the blue div does not have its value change when the theme is toggled, yet the top-level div does.

**Environment**

_environment agnostic_

**Comment by tajo** [comment]
It's probably because of this [`useMemo`](https://github.com/tajo/ladle/blob/main/packages/ladle/lib/app/src/compose-enhancers.tsx#L31), we might just need to add context into its deps. Just need to be careful to not trigger re-mounts.
