### ISSUE TITLE
styled-components not working in viewports

### ISSUE THREAD

**Issue by Em-Ant** [tajo/ladle#399]
**Describe the bug**

If using styled-components, the styles are correctly applied when the story width is unset, but not when you are in viewport mode.

**width: unset**
<img width="774" alt="image" src="https://user-images.githubusercontent.com/12955734/225301427-70482395-c2b3-41dc-af5e-340c751d5367.png">

**width: small**
<img width="774" alt="image" src="https://user-images.githubusercontent.com/12955734/225301353-11befd1f-81c4-45c3-bf03-ffd88e64c75c.png">

**Reproduction**

https://stackblitz.com/edit/ladle-3czkbf?file=src/basic.stories.tsx

**Environment**

- OS: MacOS Ventura 13.2.1
- Browser: Chrome 111.0.5563.64 (Official Build) (x86_64)
(but I don't think this problem is platform dependent)

**Comment by tajo** [comment]
Will be completely fixed with v3 to make it working out of the box. There is also an SWC styled-components plugin that can be optionally added to make the debugging easier. This will be covered in new docs.
