### ISSUE TITLE
Pressing Esc should close full screen view

### ISSUE THREAD

**Issue by wojtekmaj** [tajo/ladle#404]
**Is your feature request related to a problem? Please describe.**

I'm always confused when I enter full screen view and I - understandably so - have no UI to get me out of there.

**Describe the solution you'd like**

Pressing Esc could close the full screen view.

**Describe alternatives you've considered**

Manually editing the URL?

**Comment by tajo** [comment]
> Pressing Esc could close the full screen view.

Makes sense. 

> Manually editing the URL?

Just going back should work too.

**Comment by tajo** [comment]
We added some global hotkeys, `f` can be used to toggle full screen view: https://ladle.dev/docs/hotkeys
