### ISSUE TITLE
`tsconfig` paths not works

### ISSUE THREAD

**Issue by donrsh** [tajo/ladle#417]
**Describe the bug**

Hi. I just tried to upgrade `@ladle/react` from `v2.4.5` to `v2.11.1`, and met this problem:

![image](https://user-images.githubusercontent.com/7490144/232366841-7fc6e090-1773-4345-9e4d-9cf94b8aace6.png)

My project is a nx monorepo, and ladle is an app. `@/...` is actually a lib consumed by other apps. With the tsconfig:

```json
"compilerOptions": {
    "paths": {
      // align with apps tsconfig
      "@/*": ["../app-shared/*"],
    },
	"include": [
      "**/*",
      "./.ladle/**/*",
      "../app-shared/**/*",
    ]
  },
```

it worked quite well originally.

Looking up release logs, I wonder the problem has something to do with this [patch](https://github.com/tajo/ladle/pull/409)?

**Environment**

- OS: WSL2
- Version 2.11.1

**Comment by tajo** [comment]
Are you using yarn pnp? If so, `2.11.1` disables `vite-tsconfig-paths` in pnp environment. We had some issues with it in our internal monorepo but it might be specific to our (pretty complicated) setup. You can add it back by creating your own `vite.config.js`.

**Comment by donrsh** [comment]
Nope, I don't. But I do have customized `vite.config.ts` for configuring `pubicDir`. Might it be the cause?

```
// vite.config.js
/**
 * @type  {import("vite").UserConfig}
 */
export default {
  publicDir: "public",
};
```

**Comment by donrsh** [comment]
Hi, my case is less simpler, so I made some extractions to demo the issue: https://github.com/donrsh/issue-ladle-tsconfig-path-not-work

**Comment by tajo** [comment]
it got broken by updating `vite-tsconfig-paths@3.6.0` to `vite-tsconfig-paths@4.0.0`

going to pin it down in Ladle to `3.6.0`

in meantime, you can fix your setup by adding this into `package.json`

```
"resolutions": {
  "vite-tsconfig-paths": "3.6.0"
},
```
