### ISSUE TITLE
Allow stories at root (not in a subfolder)

### ISSUE THREAD

**Issue by Obiwarn** [tajo/ladle#422]
e.g. to prevent this:

<img width="133" alt="image" src="https://user-images.githubusercontent.com/9539797/233403502-24234c12-da59-4fdb-8813-73f91e8687ea.png">

**Comment by tajo** [comment]
This would made things pretty messy in the code when it comes to navigation and other features. It should be less annoying since we recently added some features like auto-expanding subtrees and better navigation shortcuts.
