### ISSUE TITLE
Bump Vite version

### ISSUE THREAD

**Issue by dtgreene** [tajo/ladle#443]
**Is your feature request related to a problem? Please describe.**
There was a recent [Vite vulnerability published](https://github.com/advisories/GHSA-353f-5xf4-qw67) which affects the current version used by Ladle.  I can open a PR if that's welcome but otherwise I wanted to make sure it was known.

I don't think this is a huge security risk for Ladle applications I just wanted to make that pesky warning go away.

**Describe the solution you'd like**
Bump Vite to v4.3.9

**Comment by tajo** [comment]
Feel free to open a PR
