### ISSUE TITLE
Allow more flexibility in dependency version ranges

### ISSUE THREAD

**Issue by wojtekmaj** [tajo/ladle#445]
**Is your feature request related to a problem? Please describe.**

There are several dependencies that are locked at very specific version numbers, for reasons I may be not knowlegeable enough to understand. This distrust in semver is often justified, but I'd like to ask you to reconsider more flexible dependency version ranges. For example, `vite` is locked at `4.2.something` (can't be bothered to check on mobile) and therefore, a security update to `vite` can't be automatically applied and using `@ladle/react` at the moment causes security alerts to trigger on GitHub and other platforms.

**Describe the solution you'd like**

`^x.y.z` :D

**Describe alternatives you've considered**

Yarn resolutions makes it possible to work around the issue, but it's messy and fixes the problem only in one place at a time.

**Comment by wojtekmaj** [comment]
There's no PR for unpinning vite, there's PR for updating 🤔

**Comment by tajo** [comment]
Vite is unpinned, other pins are necessary.
