### ISSUE TITLE
Default export prevents HMR

### ISSUE THREAD

**Issue by benmerckx** [tajo/ladle#453]
The default export which serves as a configuration object causes Vite to not fast refresh on changes in the story.

````tsx
export function Story() {
  return <div>story</div>
}
export default {
  title: 'Alternative title'
}
````

Whenever any code is adjusted in this file Vite will warn in the console and reload the page:

````
11:07:42 [vite] hmr invalidate /@fs/[...] Could not Fast Refresh. Learn more at https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react#consistent-components-exports
````

I'm not really sure if there's a proper workaround.

**Comment by tajo** [comment]
That's how react fast refresh operates, it's their limitation. Workarounds:

1. You don't need to define `export default` unless you want to customize the title.
2. HMR still works in other modules (e.g. components that you import into this story) - so try to keep the bulk of code outside of the story file itself.

**Comment by benmerckx** [comment]
Yeah, I figured this is unavoidable. I'll make do with the workarounds, thanks.
