### ISSUE TITLE
Keyboard navigation between stories

### ISSUE THREAD

**Issue by leyanlo** [tajo/ladle#466]
Would be nice to have keyboard shortcuts like in Storybook, where Option+arrow can move between stories or directories.

Tree navigation is pretty good with the arrow keys, but when navigating through stories that have modals or forms that steal focus, it makes it hard to jump back and forth. A dedicated Option+arrow shortcut would help in these cases.

**Comment by tajo** [comment]
Yea, modals stealing the focus really annoy me too

**Comment by leyanlo** [comment]
Yay thank you!
