### ISSUE TITLE
Ladle + Next.js (app router) - invariant expected app router to be mounted

### ISSUE THREAD

**Issue by zeekrey** [tajo/ladle#476]
**Describe the bug**

When using Ladle alongside Next.js (App Router) and `next/navigation`, an error occurs that makes Ladle unusable. The error message displayed is:

```
Uncaught Error: invariant expected app router to be mounted
```

Fortunately, Storybook encountered a similar issue and resolved it by configuring a specific parameter. You can find the solution here: [https://github.com/vercel/next.js/discussions/50068](https://github.com/vercel/next.js/discussions/50068)

**Reproduction**

* Create Next.js App (App Router)
* Install ladle
* Write a story for a component that uses `next/navigation`

**Environment**

- OS: MacOS 13.5.1
- Browser: Chrome
- Version: 116

**Comment by cm-dyoshikawa** [comment]
@tajo I'll take it!

**Comment by cm-dyoshikawa** [comment]
@tajo I would like your opinion.

I watched the reproduction in the Next.js project.

```tsx
// src/app/hello.stries.tsx

import type { StoryDefault, Story } from "@ladle/react";
import { useRouter } from "next/navigation";

export const Hello: Story = () => {
  const router = useRouter();
  return <p>Hello</p>;
};

// => "Uncaught Error: invariant expected app router to be mounted"
```

In that case, we might resolve with using decorators.

```tsx
import type { StoryDefault, Story } from "@ladle/react";
import { AppRouterContext } from "next/dist/shared/lib/app-router-context"; // Add
import { useRouter } from "next/navigation";

// Add
export default {
  decorators: [
    (Component) => {
      return (
        // @ts-expect-error
        <AppRouterContext.Provider value={{}}>
          <Component />
        </AppRouterContext.Provider>
      );
    },
  ],
} satisfies StoryDefault;

export const Hello: Story = () => {
  const router = useRouter();
  return <p>Hello</p>;
};

// => This seems working right.
```

I think that resolving dependencies using Decorators might be the responsibility of Ladle users. If we limit the support of Ladle to only React and Vite, it would probably keep the software simple. In the future, the path “next/dist/shared/lib/app-router-context” might also change, so it might be better not to hard-code it in Ladle.

Therefore, how about adding the above code as an example of using Decorators in the documentation? What do you think?

**Comment by tajo** [comment]
Yea, we should not hard-code any Next.js specific stuff into Ladle. Ideally, we provide documentation and it would be also great to create `e2e/next` project so we can have a working example + tests as well.

**Comment by cm-dyoshikawa** [comment]
@tajo Thanks. I think so too.

> e2e/next project so we can have a working example + tests as well.

I will work on considering it.

**Comment by tajo** [comment]
fix (docs) landed
