### ISSUE TITLE
After the upgrade 2.17.2 -> 3.0.0 our Jest snapshots have a new prop

### ISSUE THREAD

**Issue by moltar** [tajo/ladle#500]
I realize this is pretty vague, but I am hoping to get a lead.

Renovate Bot had updated `ladle` from `2.17.2` to `3.0.0`.

This is the only change on the PR.

We are using `pnpm`, without workspaces (monorepo).

We have a different Jest project config for React and backend code.

In a completely different part of the codebase, that isn't even related to React or frontend at all, Jest snapshot had failed.

Jest snapshot is proposing that a new prop `__nominal` has been added.

```
+             "__nominal": undefined,
```

My guess is that _some_ dep in the chain has been updated, and it is affecting Jest somehow.

![screenshot-20230920T105757-keRRWHl7@2x](https://github.com/tajo/ladle/assets/491247/f6389f2c-1dd5-4e33-9a0d-34ea32499781)

**Comment by tajo** [comment]
That's interesting. My guess would be some shared peer dependency got bumped and causing this (Ladle v3 bumped all its deps to the latest)? 

Trying to search for `__nominal` in `node_modules` could be a good start.

**Comment by moltar** [comment]
> Trying to search for `__nominal` in `node_modules` could be a good start.

Good idea!

But came up with nothing :(

```
ag -r --follow '__nominal' node_modules/
```

... _nada_ ... 🤷🏼 

I even searched entire GH for this string, and found no relevant packages that could be adding this.

https://github.com/search?q=%22__nominal%22+AND+%28language%3AJavaScript+OR+language%3ATypeScript%29+AND+NOT+path%3A.d.ts&type=code

**Comment by moltar** [comment]
Haha, jokes!! The string is in _our_ codebase 😅 

But this still does not explain why it has been all of a sudden added to the snapshot. It has been there for 3+ years.

Perhaps the snapshotting tool used to _not_ consider `__*` prefixes and now it does.

Digging further.

**Comment by moltar** [comment]
I am checking the diff of the `package.json` for these versions and nothing really jumps at me.

https://app.renovatebot.com/package-diff?name=@ladle%2freact&from=2.17.2&to=3.0.0#d2h-519664

Do you have any ideas?

All of the deps seem to be not so relevant. But maybe they are pulling in their own deps.

**Comment by tajo** [comment]
> But maybe they are pulling in their own deps.

This probably.

**Comment by tajo** [comment]
I don't think there's anything we can do on our side?
