### ISSUE TITLE
Side panel story name not readable when using longer names or folder nesting

### ISSUE THREAD

**Issue by Hurtak** [tajo/ladle#516]
**Is your feature request related to a problem? Please describe.**
We use Ladle for large amount of components, so we had to introduce a decent amount of folder nesting, the problem is that after around 4 levels of folders the component names stop being readable because of not enough space in the side bar

<img width="817" alt="image" src="https://github.com/tajo/ladle/assets/6587821/21a4ea3f-5a8a-425b-a2d3-4cc7b2d74fc7">
 
**Describe the solution you'd like**
Some combination 
- reducing spacing in the side panel - so there would be more space for story name
- add a drag resize feature to the panel (ideally with saving the width of the panel into local storage)

**Comment by tajo** [comment]
> reducing spacing in the side panel - so there would be more space for story name

You can [tweak](https://ladle.dev/docs/config#appendtohead) the default CSS stylesheet. Should be pretty straightforward.

> add a drag resize feature to the panel (ideally with saving the width of the panel into local storage)

Yea, I've been wanting this for a while as well.
