### ISSUE TITLE
Toggling view should retail the filter query

### ISSUE THREAD

**Issue by phaistonian** [tajo/ladle#555]
When pressing `f` to toggle full-screen, retain the filter string (query) so that the filtering will remain there upon returning to the standard view.

The lack of carrying the query makes the experience painful when dealing with many stories.

Also, restoring the scroll position in the stories container will improve UX.

Ps: apologies for ignoring the issue template.

**Comment by tajo** [comment]
fixed, scheduled for a release

**Comment by phaistonian** [comment]
@tajo  Any ETA on the new release?

**Comment by tajo** [comment]
by the end of year, going to a bigger release with React 19 and Vite v6

**Comment by phaistonian** [comment]
Great release, @tajo :)

Is there any chance of an option to preserve the query in the URL (e.g., `q=query`) so that it's shareable and so that refreshing the page won't lose it?

**Comment by tajo** [comment]
@phaistonian yea, that would be a nice feature if anyone wants to implement it
