### ISSUE TITLE
How to use .env variables?

### ISSUE THREAD

**Issue by petyosi** [tajo/ladle#57]
Ladle looks great, trying it as a testbed for playwright. Is there any way to access the variables in the `.env` file? I noticed that doing something like `VITE_VAR=foo yarn ladle serve` works.

**Comment by tajo** [comment]
https://github.com/tajo/ladle/issues/57 exposes `.env` files and adds some documentation about env variables and global constant replacements. 

GitHub is having a [partial outage](https://www.githubstatus.com/incidents/fpk08rxnqjz2) so can't release a new version yet. 😭

**Comment by tajo** [comment]
released as `@ladle/react@0.8.4`

**Comment by tajo** [comment]
docs: https://www.ladle.dev/docs/config/#env-variables-and-modes

**Comment by petyosi** [comment]
Thanks for the lightning-fast resolution. I will test tomorrow.
