### ISSUE TITLE
Use outside an existing project?

### ISSUE THREAD

**Issue by aadrian** [tajo/ladle#575]
Hi,

Can Ladle be used **outside** of an existing project easily?
If yes, are there any links/docs how to achieve this? _( I could not find any :( )._

In many situations, it is not desired/allowed  that the storybooks are part of the repo/project itself, but need to  be separated:
- components are distributed across several GIT projects, but only one "storybook" Test Project/deployment is required.
- many projects are done by other teams than those doing the storybooks, and even there's mostly **read-only** access to the  project with components being tested.
- besides read-only repos, the dependencies/changes introduced by storybooks are not allowed to be committed in the same GIT repository.

Thank you!

**Comment by tajo** [comment]
not really, we are probably limited by vite needing to have access to single project's `node_modules` to resolve all dependencies

**Comment by aadrian** [comment]
@tajo since Vite would have access to the components sources, it also has access to the "package.json"  . Wouldn't that be enough?
