### ISSUE TITLE
MDX support 

### ISSUE THREAD

**Issue by uicowboy** [tajo/ladle#58]
Hello! It's mentioned in the docs that you have plans to add support for MDX to Ladle. Our team uses Storybook but we don't use CSF, rather we write all of our component stories in MDX and basically just use Storybook for rendering and building the stories. 

Just out of curiosity, what would support for MDX look like in Ladle? Is this work already ongoing?

Thanks!

**Comment by tajo** [comment]
> what would support for MDX look like in Ladle?

We have many Storybook instances that use `addon-docs` and MDX, so Ladle's support is important and will mimic Storybook as much as it makes sense. It's a pretty extensive addon so some less used features might be left out inititally but in general it should be very similar.

> Is this work already ongoing?

Starting.

**Comment by R-Bower** [comment]
Is there an issue tracker for this?  I'm eager to convert over to ladle but need MDX support.

**Comment by tajo** [comment]
You can follow this issue.

**Comment by trekinbami** [comment]
Any updates on this perhaps? Any help needed? This is the only feature that's blocking us from adopting ladle.

**Comment by tajo** [comment]
After the config overhaul it's the top priority. (that and CSF3) Likely a few more weeks.

**Comment by cfcomputing** [comment]
Are you looking for any help to move this forward, echoing other sentiments here that this is the only thing currently blocking adoption for me, and willing to help get this added if you are looking for contributors, thanks!

**Comment by tajo** [comment]
I want to announce it at [ViteConf](https://viteconf.org/schedule/introducing_ladle_develop_and_test_your_react_stories_faster) next month, so it needs to be done by that. 😅

> help get this added if you are looking for contributors

For the start, it would be helpful to write a documentation / spec to define the scope.

**Comment by tajo** [comment]
[Documentation](https://ladle.dev/docs/mdx)
