### ISSUE TITLE
import aliases?

### ISSUE THREAD

**Issue by DanielFGray** [tajo/ladle#59]
in my tsconfig I have
```js
{
    "baseUrl": ".",
    "paths": {
      "~/*": ["./app/*"]
    },
}
```
and out of the box, when importing stories that use this import format I get "failed to resolve import" errors, which makes sense

seeing as ladle is based on vite, I looked up how to enable import aliases through vite, and found I can create a `vite.config.js` like so:
```js1
import { defineConfig } from 'vite'
import path from 'path'

export default defineConfig({
  resolve: {
    alias: {
      '~': path.resolve(__dirname, './app'),
    },
  },
})
```

however this doesn't seem to have any effect on import resolution in ladle and I still get the same error
```
11:50:35 AM [vite] Internal server error: Failed to resolve import "~/utils/classNames" from "app/components/Forms.tsx". Does the file exist?
```

**Comment by DanielFGray** [comment]
thanks. is there a fix for making this work in `.ladle/components.tsx` so I can
```js
import '~/styles/tailwind.css'
```

**Comment by ibgrav** [comment]
I was having trouble with the alias being absolute as opposed to relative.
It looks like `config.mjs` is not transformed by vite in `load-config.js`. I think that may solve some of these issues, but haven't looked much into it so apologies for my assumptions.

Since `path.resolve(__dirname, './app')` was not working for `.ladle/config.mjs`, I solved this by using `import.meta.url`:
```javascript
const url = new URL(import.meta.url);

export default {
  resolve: {
    alias: {
      "@": url.pathname.replace(".ladle/config.mjs", "src"),
    },
  },
}
```

**Comment by tajo** [comment]
> Does this lib not use vite as close as it should?

Not sure what this means. Ladle uses Vite but doesn't expose all the configuration options.

`vite-tsconfig-paths`  - I can add this plugin, seems pretty useful.

What do you need `jsxInject` for?

**Comment by coreylight** [comment]
Ok! I think exposing all options would clear up some confusion or allow for advanced users to customize easier...
My `jsxInject` looks like this currently:
`import { jsx } from '@emotion/react';import React from 'react'`

**Comment by essejmclean** [comment]
A fix for this would be fantastic.

I'm currently unable to render components that reference files using `@/*` like `@/components`. For instance, I have a component called `Tag` that references another component called `Tag` via `import { Text } from "@/components"`.

Just doesn't render anything right now and have tried a number of options via Vite and solutions here. I think the issue may be related to the `vite-tsconfig-paths` plugin missing (I'm using TSX).

**Comment by cr0cK** [comment]
Similar issue and after tweaking a lot, I manage to make it work:

Here my `.ladle/config.mjs` file:

```js
const url = new URL(import.meta.url)

const [, absPath] = url.pathname.match(/^(.*)\/.ladle/)

function getFullPath(relativePath) {
  return `${absPath}/${relativePath}`
}

const config = {
  resolve: {
    alias: [
      {
        find: /^@app\/(.*)/,
        replacement: getFullPath('src/app/$1')
      },
      {
        find: /^@libs\/(.*)/,
        replacement: getFullPath('src/libs/$1')
      },
      {
        find: /^@styles\/(.*)/,
        replacement: getFullPath('src/styles/$1')
      },
      {
        find: /^@@types\/(.*)/,
        replacement: getFullPath('src/types/$1')
      }
    ]
  }
}

export default config
```

**Comment by zanona** [comment]
It would be great to avoid duplication and load aliases from tsconfig the same way vite does?

**Comment by tajo** [comment]
> It would be great to avoid duplication and load aliases from tsconfig the same way vite does?

Agree. Going to add the tsconfig plugin.
