### ISSUE TITLE
Support for React 19

### ISSUE THREAD

**Issue by praseodym** [tajo/ladle#590]
[React 19 has been released](https://react.dev/blog/2024/12/05/react-19) and Ladle does not seem to be compatible yet.

When trying to update, `react-inspector` is incompatible according to npm. There is an issue for this: https://github.com/storybookjs/react-inspector/issues/185.

**Comment by tajo** [comment]
Will add the support by the end of year with some other major changes (Vite v6).

**Comment by tajo** [comment]
implemented in https://github.com/tajo/ladle/pull/591

**Comment by praseodym** [comment]
The lack of support for React 19 in `react-inspector` still creates a dependency conflict with Ladle 5.0.0:

```
> npm install
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: react-inspector@6.0.2
npm warn Found: react@19.0.0
npm warn node_modules/react
npm warn   react@"^19.0.0" from the root project
npm warn   6 more (@ladle/react, @ladle/react-context, @mdx-js/react, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer react@"^16.8.4 || ^17.0.0 || ^18.0.0" from react-inspector@6.0.2
npm warn node_modules/@ladle/react/node_modules/react-inspector
npm warn   react-inspector@"^6.0.2" from @ladle/react@5.0.0
npm warn   node_modules/@ladle/react
npm warn
npm warn Conflicting peer dependency: react@18.3.1
npm warn node_modules/react
npm warn   peer react@"^16.8.4 || ^17.0.0 || ^18.0.0" from react-inspector@6.0.2
npm warn   node_modules/@ladle/react/node_modules/react-inspector
npm warn     react-inspector@"^6.0.2" from @ladle/react@5.0.0
npm warn     node_modules/@ladle/react
```

This is from a simple test project with the following dependencies:

```json
  "dependencies": {
    "@ladle/react": "^5.0.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  }
```

**Comment by tajo** [comment]
It's just a warning but should function fine?

**Comment by praseodym** [comment]
It does work, but the conflicting peer dependency is a blocker for us. We configured npm with the [`strict-peer-deps`](https://docs.npmjs.com/cli/v7/using-npm/config#strict-peer-deps) option to prevent e.g. Dependabot accidentally breaking dependencies.

**Comment by tajo** [comment]
convo can continue here: https://github.com/tajo/ladle/issues/590#issuecomment-2605154415

**Comment by praseodym** [comment]
> convo can continue here: [#590 (comment)](https://github.com/tajo/ladle/issues/590#issuecomment-2605154415)

I think you meant to link to #597. Let's continue there!
