### ISSUE TITLE
Stories do not auto reload

### ISSUE THREAD

**Issue by robcaldecott** [tajo/ladle#62]
This is looking great so far, great work.

One issue, if I update a story file (e.g. by adding a new export) ladle does not auto refresh.
However, editing a component that the story references does cause a reload.

Have I missed a setting that would stop edits to a `stories.tsx` file from refreshing?

**Comment by tajo** [comment]
I know that adding/removing story (export from `*.stories.tsx`) doesn't automatically reload/refresh the page. Something to improve for sure. Also the same when it comes to config, components.tsx.

**Comment by tsingson** [comment]
> This is looking great so far, great work.
> 
> One issue, if I update a story file (e.g. by adding a new export) ladle does not auto refresh. However, editing a component that the story references does cause a reload.
> 
> Have I missed a setting that would stop edits to a `stories.tsx` file from refreshing?

yet, same issue and:

* automatic refresh new stories when ladle running
* cascade, recursive support stories in subdirectory


ps:  great work, thks a lot

**Comment by mbarzeev** [comment]
Same here.
Aside from that this really looks promising, thanks for the great work!
