### ISSUE TITLE
Overwriting glob, no stories found

### ISSUE THREAD

**Issue by rnnyrk** [tajo/ladle#70]
HI there,

I wanted to tryout Ladle, although my components are not found in the src folder. Therefore I wanted to overwrite the default glob, but unfortunately Ladle doesn't seem to pickup the change. Happening both via CLI as well as via the config file. Any thought?

<img width="2242" alt="Screenshot 2022-03-23 at 10 08 22" src="https://user-images.githubusercontent.com/4519142/159663884-b72ace97-0b3c-40bb-a3c3-3bbb0deb4f3c.png">

**Comment by tajo** [comment]
We could improve the page message a bit so it's more obvious that your stories glob is not set correctly.

**Comment by tajo** [comment]
We could improve the page message a bit so it's more obvious that your stories glob is not set correctly.
