### ISSUE TITLE
Single story hoisting

### ISSUE THREAD

**Issue by nihgwu** [tajo/ladle#74]
Just tried out Ladle, that what I wanted to build years ago because SB is too slow and the bundle size is too big

[Single story hoisting](https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy#single-story-hoisting) is the one I missed most

another one is how to inject preview header? I use it to inject google fonts, it would be nice that we can customise the layout

**Comment by tajo** [comment]
> [Single story hoisting](https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy#single-story-hoisting) is the one I missed most

This seems pretty arbitrary, why not just to update the default title?

> another one is how to inject preview header?

You should be able to do that through `.ladle/components.tsx`: https://www.ladle.dev/docs/providers

You can add there `useEffect` to inject additional tags into the `head` or use library like react-helmet.

**Comment by nihgwu** [comment]
![image](https://user-images.githubusercontent.com/2595058/160205197-28ed8885-5a68-4e4c-9553-f493fc69b1c0.png)
I would love to have the default story be hoisted, yes I managed to make them hoisted by changing the title to `components` and set `storyName` as component name

> You can add there useEffect to inject additional tags into the head or use library like react-helmet.

yes I can change anything programatically but it would be nice config it directly, for example the document title
