### ISSUE TITLE
Base vite-config overrides the default esbuild loader for ts/tsx

### ISSUE THREAD

**Issue by lindskogen** [tajo/ladle#76]
Hello! I noticed that the base vite-config overrides the default esbuild loader for ts/tsx.

https://github.com/tajo/ladle/blob/master/packages/ladle/lib/cli/vite-base.js#L73

This causes errors in `.ts` files that are using `.ts`-specific syntax, for example:

```
The character ">" is not valid inside a JSX element
81 |    value: TValue,
82 |    options: UseCellOptions<TValue>
83 |  ): SomeResult<TValue> => {
   |                         ^
```

Is there a specific reason for this or can it be removed?

**Comment by tajo** [comment]
https://github.com/tajo/ladle/pull/89
