### ISSUE TITLE
[DISCUSSION]  Add Docs views like storybook ?

### ISSUE THREAD

**Issue by siva-sundar** [tajo/ladle#79]
First of all, thanks for working on this project, this looks promising !

I am unable to find a way to view the docs and code section of the stories. Do we have plans to them in the future ?

Would love to contribute on that.

Any help on this would be really appreciated, TIA.

**Comment by tajo** [comment]
> view the docs

Something we want to add soon.

> nice to export sourceCode in meta

Are we talking about the source code of stories only? It would probably have to be an opt-in setting to keep the file size of meta reasonable.

**Comment by tajo** [comment]
FYI: Source Code addon has been already added.

**Comment by tajo** [comment]
we have some basic MDX support already (adding documentation soon), currently not planning supporting more docs features/special docs view

the next focus will be auto-generating documentation and controls from typescript
