### ISSUE TITLE
Is the public repository served?

### ISSUE THREAD

**Issue by kingjack05** [tajo/ladle#81]
I store the font files as local assets under the `/public` directory, but when I try to import them from stories I get a "failed to load resources" error.

**Comment by tajo** [comment]
Can you create a repro with https://node.new/ladle ? Thanks

**Comment by arthurdenner** [comment]
@kingjack05, once #72 is merged, `/public` will be served by default with the possibility to set it [like in `vite`](https://vitejs.dev/config/#publicdir).
