### ISSUE TITLE
[PROPOSAL]: New layout

### ISSUE THREAD

**Issue by vinpac** [tajo/ladle#82]
Hey 👋

I love Ladle already. Its focus on performance is something I always wanted to see in Storybook. So, I wanna help it give a step forward to have a UI that matches its awesome engineering layers. 

Here's is the design I made:

**Light** 
![Light](https://user-images.githubusercontent.com/9030018/160306239-df8c55ba-a34c-4d4b-9b01-7d2732c0cbd2.jpg)

**Dark** 
![Dark](https://user-images.githubusercontent.com/9030018/160306241-9870fd65-2085-47cd-8a8d-8669939a856a.jpg)

Here are the steps I imagined for this project:
- [x] Design the new UI
- [x] Collect feedbacks 
- [x] Implement changes on the design after feedback
- [x] Start PR with the new layout
- [ ] Finish first version of PR
- [ ] Get the PR Reviewed
- [ ] Implement requested changes
- [ ] Get the PR merged

If this layout is not what you expect, please, feel free to express your feelings.
Thanks for the attetion.

**UPDATE**
The PR is now open #101 as a draft

**Comment by vinpac** [comment]
Seeing @wojtekmaj, I think Ladle deserves a more original look. It's not much, but I did a little tweak. Here's my take on mobile view too:


![Light](https://user-images.githubusercontent.com/9030018/160432965-20b90057-7e6a-44c3-b6a2-f40aa99acd0d.jpg)


![13 Pro - 1](https://user-images.githubusercontent.com/9030018/160432937-4646ea86-eb88-4bf9-862e-0ae49fe2f386.jpg)

![13 Pro - 2](https://user-images.githubusercontent.com/9030018/160432943-818eb6c4-9dc8-43c9-9c46-b6b41cb2495e.jpg)

**Comment by tajo** [comment]
Looks nice! I like the second version more since there is a more straightforward connection between the addon button and addon panel itself. Also, I would make the elements and text a bit bigger. 

Some other notes:

1. It would be nice if the theme could be just an alternate swappable CSS (configurable through the config). So we can have multiple options, including the current one. We can reorganize the current layout's HTML if needed.
2. It needs to be responsive. So any theme should capture mobile, desktop, light and dark versions.

**Comment by vinpac** [comment]
Sure @tajo. Thanks for the feedback. I will draft the PR implementing it

**Comment by hennessyevan** [comment]
I also like the second one with the status bar, I think that's really great.

Can we take this top-level section heading UI from storybook? Looking at the designs in this thread it seems like the intent and a popular organizational approach is to have meta sections like "atoms" "molecules", etc. Having those as folders (especially that are collapsed by default) makes it hard to locate and discover components.

<img width="165" alt="image" src="https://user-images.githubusercontent.com/16711653/162989255-20f7d1f0-d143-481a-ab4c-0af14a702009.png">
