### ISSUE TITLE
Do not normalise storyName

### ISSUE THREAD

**Issue by nihgwu** [tajo/ladle#83]
![image](https://user-images.githubusercontent.com/2595058/160382013-e71a148d-3d07-4ea4-9880-0fcc2fdd106f.png)

I think we should only normalise if it's from filename, if we set it explicitly by `title`/`storyName` we should use it directly

**Comment by wojtekmaj** [comment]
Yep. Normalizing storyName may even crash Ladle completely.

Example: I've had this bit copied over from Storybook:

```js

export const ValueString = Template.bind({});
ValueString.storyName = 'Default (value passed as string)';
ValueString.args = {
  ...Default.args,
  defaultValue: formatISODate(today),
};

export const ValueStringArr = Template.bind({});
ValueStringArr.storyName = 'Default (value passed as string[])';
ValueStringArr.args = {
  ...Default.args,
  defaultValue: [today, in30Days].map(formatISODate),
};
```

And I got:

```
14:51:03 [vite] Internal server error: /node_modules/@ladle/react/lib/app/generated/generated-list.tsx: Identifier 'components$$form$elements$$daterange$$default$value$passed$as$string$' has already been declared. (1170:6)
```

**Comment by tajo** [comment]
@wojtekmaj Story names are used as identifiers/component names for internal purposes. In your case, it gets normalized into the same ID and that crashes it.  We should provide a better error message.

For the OP issue, we could add an additional `displayTitle` param to preserve the name in the sidenav.

**Comment by tajo** [comment]
[This PR](https://github.com/tajo/ladle/pull/135) addresses @wojtekmaj issues - it make sures that all parsing errors are properly surfaced and user-friendly, includes a special landing page explaining details.

**Comment by nihgwu** [comment]
So that PR shouldn't close this issue I think
