### ISSUE TITLE
Testing aspect of Ladle

### ISSUE THREAD

**Issue by kfrajtak** [tajo/ladle#85]
> Ladle is an environment to develop, **test** and share your React components faster.

My question is how to test the components?

**Comment by tajo** [comment]
We should add some docs about testing strategies. 

TLDR; Stories can be unit tested through a library like https://testing-library.com/docs/react-testing-library/intro/ and end-to-end with [Playwright](https://playwright.dev/)

https://www.ladle.dev/docs/meta#testing

**Comment by tajo** [comment]
https://ladle.dev/blog/visual-snapshots
