### ISSUE TITLE
Use Yarn v3 instead of legacy v1

### ISSUE THREAD

**Issue by wojtekmaj** [tajo/ladle#86]
Looks like we can shave 20-25 seconds off CI & publish job thanks to faster installs & caching, but benefits just start here. Read more:

https://threadreaderapp.com/thread/1486318477203881985.html

I would be happy to help with the update.
Thoughts?

**Comment by tajo** [comment]
Yea, I am not against it. 

I had some problems running node ESM scripts through yarn v2 but it might be addressed in newer versions (pnp esm node APIs were experimental).

**Comment by tajo** [comment]
One extra concern is the usage of [husky](https://typicode.github.io/husky/#/?id=yarn-2) (recently added), it works differently in yarn v1 vs v2

**Comment by nihgwu** [comment]
I think the majority still stay with Yarn v1, or just turn to pnpm, so from contribution's perspective, It would be nicer to stay with V1 as well, until we are going to try something different

**Comment by wojtekmaj** [comment]
I'm running husky perfectly fine on Yarns v3.

Also, I'm not really advocating for PnP actually - I still consider it a novelty and some important parts of the ecosystem still have trouble handling it. It's a nice initiative to push the ecosystem forward, but not as a daily driver in a serious project IMO.

I'd still like to use node_modules resolver.

**Comment by jrkienle** [comment]
Have we considered [pnpm](https://pnpm.io/)? That might be an easier lift than yarn 1 -> 3 and still shave a considerable amount off the build time

**Comment by wojtekmaj** [comment]
Updated Yarn to v3 on my working branch in a couple of minutes, that isn't a problem

**Comment by tajo** [comment]
Switched to pnpm v7 and turborepo.
