### ISSUE TITLE
Imported CSS messes up with Ladle's sidebar

### ISSUE THREAD

**Issue by Macxim** [tajo/ladle#92]
I just imported my CSS file like this: `import "./styles.css";` and now the elements in the sidebar are misaligned.
Is there any way the imported `styles.css` can be applied only inside `.ladle-main`?

![Screen Shot 2022-03-30 at 10 31 36 PM](https://user-images.githubusercontent.com/1909957/160934722-583a235d-7762-4029-a72b-ed4e71385496.png)

**Comment by tajo** [comment]
Can your create a repro? https://node.new/ladle

We don't use an `iframe` so your styles can impact the Ladle's UI. There are probably two solutions we could consider:

1. We could make the stylesheet for Ladle exhaustive (pretty much a CSS reset on each element).
2. Maybe we could add an option to prefix all imported styles with `.ladle-main` when being loaded with Vite.

**Comment by Macxim** [comment]
Well, I haven't edited anything yet (no custom styles) and it's still looks like this for me on latest Firefox and Brave.

https://stackblitz.com/edit/ladle-8hzm53
![Screen Shot 2022-03-31 at 5 41 14 AM](https://user-images.githubusercontent.com/1909957/160977982-00379b19-9e21-4960-ac14-8c025dca739e.png)

--- 

Here is another repro with the issue I'm experiencing https://stackblitz.com/edit/ladle-87j3su 
![Screen Shot 2022-03-31 at 6 00 08 AM](https://user-images.githubusercontent.com/1909957/160979924-1224311f-f048-4071-bdb4-d1c6c779f162.png)
