### ISSUE TITLE
Global component args

### ISSUE THREAD

**Issue by ChewbaccaCookie** [tajo/ladle#96]
Hi,
is there the possibility to apply arguments to the `.ladle/components.tsx` component?
I'm using a global context provider, which allows to change theme and language. 
Therefore it would be great to toggle globally this properties.

Thank you for your great project!

**Comment by tajo** [comment]
There is no support for global args yet. As a workaround, you could add some state and UI elements to the `components.tsx`'s Provider.

**Comment by ChewbaccaCookie** [comment]
Okay thank you for your fast response :)
