### ISSUE TITLE
No custom config found

### ISSUE THREAD

**Issue by thecoorum** [tajo/ladle#98]
## Description
After installing `@ladle/react-cjs` I created a custom config at `.ladle/config.mjs` with
```
export default {
  stories: 'webpack/ui/components/**/stories.{js,jsx}',
  root: '../',
  ...
}
```
When I'm running the ladle with `yarn ladle serve` in the opened window I can see that the configured glob pattern for stories is the same as I specified in config file, but no stories found. And if I run ladle with debug mode I can see that CLI says that no custom config found

**Comment by tajo** [comment]
Can you reproduce this with https://node.new/ladle?
