### ISSUE TITLE
Type checking stories

### ISSUE THREAD

**Issue by danielyogel** [tajo/ladle#99]
Storybook supports a `typescript: { check: true }` config option, which type checks the stories when building/developing the stories, and not only when opening  a story in VSCode.

This is very helpful, and would improve Ladle a lot.

**Comment by tajo** [comment]
You could probably add this plugin into config: https://github.com/fi3ework/vite-plugin-checker

Personally, I prefer having `tsc` as a different script/process that's enforced by the CI and VS Code for local dev.
